// 화해 리뷰 랭킹 기반 실제 제품 데이터 (별점은 참고용 근사값).
// fullMl/price 는 카테고리 기준 근사값(수정 가능), oliveYoungUrl 은 제품명 검색 링크.
// image: 실제 제품 이미지 URL을 넣으면 노출, 비어 있으면 브랜드 컬러 플레이스홀더로 폴백.

import { allergyRiskForProduct } from "./allergens-data";
import productsRegistry from "../data/products.json";

// cosmetic_id → 전성분(전수, data/products.json) 조회 — 직접 입력한 알러지 자유 텍스트를
// 짧은 마케팅 성분 태그(Cosmetic.ingredients)뿐 아니라 전성분표까지 대조하기 위해 쓴다.
const INCI_BY_COSMETIC_ID: Record<string, string[]> = Object.fromEntries(
  (productsRegistry as { cosmetic_id: string; ingredients_inci: string[] }[]).map((e) => [e.cosmetic_id, e.ingredients_inci])
);
export function fullIngredientsFor(cosmeticId: string): string[] | undefined {
  return INCI_BY_COSMETIC_ID[cosmeticId];
}

export type Cosmetic = {
  id: string;
  brand: string;
  brandJp?: string; // 일본어 브랜드명 (언어 전환용, 없으면 brand로 폴백)
  brandEn?: string; // 영어 브랜드명 (언어 전환용, 없으면 brand로 폴백)
  name: string;
  nameJp?: string; // 일본어 제품명 (언어 전환용, 없으면 name으로 폴백)
  nameEn?: string; // 영어 제품명 (언어 전환용, 없으면 name으로 폴백)
  category: string; // 세럼/크림/토너/앰플/클렌징/선크림/마스크팩/로션
  ingredients: string[];
  forTypes: string[]; // 건성/지성/복합/중성/민감
  concerns: string[]; // 주름/기미/수분/트러블
  rating: number;
  feel: string; // 산뜻/보습/진정/촉촉
  desc: string;
  descJp?: string; // 일본어 설명 (언어 전환용, 없으면 desc로 폴백)
  descEn?: string; // 영어 설명 (언어 전환용, 없으면 desc로 폴백)
  fullMl: number; // 정품 용량
  price: number; // 정가(원, 근사·참고용)
  safety: string[]; // 약산성/무향/저자극/무기자차 등
  oliveYoungUrl: string;
  linkType: "direct" | "search"; // direct=개별 상품페이지, search=검색 폴백
  image?: string;
};

// 올리브영 실제 판매 제품 기반 큐레이션 (실시간 연동 아님). 정가는 근사·참고용.
export const COSMETICS: Cosmetic[] = [
  { id: "roundlab-dokdo-toner", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "1025 독도 토너", nameJp: "1025 独島 トナー", nameEn: "1025 Dokdo Toner", category: "토너", ingredients: ["미네랄", "진정"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "산뜻", desc: "자극 없이 결을 정돈하는 진정 토너", descJp: "刺激なく肌理を整える鎮静トナー", descEn: "A soothing toner that smooths texture without irritation.", fullMl: 200, price: 15000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000132162", linkType: "direct", image: "/assets/products/roundlab-dokdo-toner.webp" },
  { id: "toriden-divein-cleansing", brand: "토리든", brandJp: "トリデン", brandEn: "Torriden", name: "다이브인 저분자 히알루론산 클렌징 폼", nameJp: "ダイブイン 低分子ヒアルロン酸洗顔フォーム", nameEn: "Dive-In Low Molecular Hyaluronic Acid Cleansing Foam", category: "클렌징", ingredients: ["히알루론산", "저분자"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.7, feel: "촉촉", desc: "세안 후에도 당기지 않게 속보습을 남기는 저자극 폼", descJp: "洗顔後もつっぱらず潤いを残す低刺激泡洗顔料", descEn: "A low-irritation foam cleanser that leaves skin hydrated, not tight.", fullMl: 150, price: 16000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("토리든 다이브인 저분자 히알루론산 클렌징 폼"), linkType: "search" },
  { id: "esnature-aqua-rice-cleansing", brand: "에스네이처", brandJp: "エスネイチャー", brandEn: "Esnature", name: "아쿠아 라이스 약산성 클렌징 폼", nameJp: "アクアライス 弱酸性洗顔フォーム", nameEn: "Aqua Rice pH-Balanced Cleansing Foam", category: "클렌징", ingredients: ["쌀추출물", "약산성"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.7, feel: "산뜻", desc: "쌀 성분으로 순하게 씻어내는 약산성 데일리 폼", descJp: "米由来成分でやさしく洗い流す弱酸性デイリー泡洗顔料", descEn: "A weakly-acidic daily foam with rice extract for a gentle cleanse.", fullMl: 160, price: 19000, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("에스네이처 아쿠아 라이스 약산성 클렌징 폼"), linkType: "search" },
  { id: "shenli-kelp-cleansing", brand: "션리", brandJp: "シェンリー", brandEn: "Shenli", name: "다시마 앰플 클렌징폼", nameJp: "昆布アンプル洗顔フォーム", nameEn: "Kelp Ampoule Cleansing Foam", category: "클렌징", ingredients: ["다시마", "미네랄"], forTypes: ["지성", "복합", "중성"], concerns: ["수분", "트러블"], rating: 4.5, feel: "촉촉", desc: "다시마 앰플 성분으로 세안 후에도 속당김 없이 촉촉하게", descJp: "昆布アンプル成分で洗顔後もつっぱらずしっとり", descEn: "Kelp ampoule ingredients keep skin comfortably hydrated after cleansing.", fullMl: 120, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("션리 다시마 앰플 클렌징폼"), linkType: "search" },
  { id: "suiskin-sprout-cleansing", brand: "수이스킨", brandJp: "スイスキン", brandEn: "Suiskin", name: "어린새싹 딥 클렌징 폼", nameJp: "若葉ディープクレンジングフォーム", nameEn: "Young Sprout Deep Cleansing Foam", category: "클렌징", ingredients: ["새싹추출물"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.6, feel: "산뜻", desc: "모공 속 노폐물까지 개운하게 씻어내는 딥 클렌징 폼", descJp: "毛穴の奥の汚れまですっきり洗い流すディープクレンジングフォーム", descEn: "A deep-cleansing foam that clears out pore buildup.", fullMl: 150, price: 14000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("수이스킨 어린새싹 딥 클렌징 폼"), linkType: "search" },
  { id: "illiyoon-ceramide-wash", brand: "일리윤", brandJp: "イルリユン", brandEn: "Illiyoon", name: "세라마이드 아토 6.0 탑투토 워시", nameJp: "セラミド アト6.0 トップトゥトゥウォッシュ", nameEn: "Ceramide Ato 6.0 Top-to-Toe Wash", category: "클렌징", ingredients: ["세라마이드"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.7, feel: "보습", desc: "얼굴부터 몸까지, 순하게 세안하며 장벽을 지키는 약산성 워시", descJp: "顔から体まで、やさしく洗いながらバリアを守る弱酸性ウォッシュ", descEn: "A weakly-acidic wash for face and body that protects the skin barrier while cleansing gently.", fullMl: 500, price: 14000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("일리윤 세라마이드 아토 6.0 탑투토 워시"), linkType: "search" },
  { id: "ahc-herb-rose-toner", brand: "AHC", brandJp: "AHC", brandEn: "AHC", name: "허브솔루션 로즈 토너", nameJp: "ハーブソリューション ローズトナー", nameEn: "Herb Solution Rose Toner", category: "토너", ingredients: ["다마스크장미꽃수"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "다마스크 장미꽃수로 산뜻하게 결을 정돈하는 대용량 토너", descJp: "ダマスクローズ水でさっぱりと肌理を整える大容量トナー", descEn: "A large-capacity toner with Damask rose water for a refreshed texture.", fullMl: 500, price: 13800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165364", linkType: "direct", image: "/assets/products/ahc-herb-rose-toner.webp" },
  { id: "numbuzin-no3-toner", brand: "넘버즈인", brandJp: "ナンバーズイン", brandEn: "Numbuzin", name: "3번 보들보들 퍼스트 결부스팅 토너", nameJp: "3番 もちもちファーストトナー", nameEn: "No.3 Soft Skin First-Texture Boosting Toner", category: "토너", ingredients: ["나이아신아마이드", "세라마이드", "판테놀"], forTypes: ["지성", "복합", "중성"], concerns: ["수분", "트러블"], rating: 4.5, feel: "산뜻", desc: "나이아신아마이드로 피부결을 정돈하는 자극 없는 데일리 토너", descJp: "ナイアシンアミドで肌理を整える低刺激デイリートナー", descEn: "A gentle daily toner with niacinamide to refine texture.", fullMl: 200, price: 24000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000250711", linkType: "direct", image: "/assets/products/numbuzin-no3-toner.webp" },
  { id: "abib-heartleaf-toner", brand: "아비브", brandJp: "アビブ", brandEn: "Abib", name: "어성초 카밍 토너 스킨 부스터", nameJp: "ドクダミ カーミングトナー スキンブースター", nameEn: "Heartleaf Calming Toner Skin Booster", category: "토너", ingredients: ["어성초추출물", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "지리산 어성초 추출물로 열감을 식혀주는 쿨링 진정 토너", descJp: "智異山ドクダミ抽出物でほてりを鎮めるクーリング鎮静トナー", descEn: "A cooling, soothing toner with Jiri Mountain heartleaf extract.", fullMl: 200, price: 23000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000155253", linkType: "direct", image: "/assets/products/abib-heartleaf-toner.jpg" },
  { id: "drg-aclear-toner", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "에이클리어 밸런싱 토너", nameJp: "エークリア バランシングトナー", nameEn: "A-Clear Balancing Toner", category: "토너", ingredients: ["살리실산", "마데카소사이드"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.52, feel: "산뜻", desc: "과잉 피지와 각질을 정돈하는 약산성 저자극 토너", descJp: "過剰な皮脂と角質を整える弱酸性低刺激トナー", descEn: "A weakly-acidic, low-irritation toner that clears excess sebum and buildup.", fullMl: 200, price: 25000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165710", linkType: "direct", image: "/assets/products/drg-aclear-toner.webp" },
  { id: "ahc-herb-witchhazel-toner", brand: "AHC", brandJp: "AHC", brandEn: "AHC", name: "허브솔루션 위치하젤 토너", nameJp: "ハーブソリューション ウィッチヘーゼルトナー", nameEn: "Herb Solution Witch Hazel Toner", category: "토너", ingredients: ["위치하젤"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.2, feel: "산뜻", desc: "위치하젤로 모공과 피지를 산뜻하게 정돈하는 토너", descJp: "ウィッチヘーゼルで毛穴と皮脂をさっぱり整えるトナー", descEn: "A witch hazel toner that refreshes pores and sebum.", fullMl: 500, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165355", linkType: "direct", image: "/assets/products/ahc-herb-witchhazel-toner.webp" },
  { id: "blancdoux-oligo-toner", brand: "더랩바이블랑두", brandJp: "ザ・ラボ バイ ブランドゥ", brandEn: "The Lab by Blanc Doux", name: "올리고 히알루론산 저분자 딥 토너", nameJp: "オリゴヒアルロン酸 低分子ディープトナー", nameEn: "Oligo Hyaluronic Acid Low-Molecular Deep Toner", category: "토너", ingredients: ["올리고히알루론산", "히알루론산"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.7, feel: "촉촉", desc: "저분자 히알루론산이 각질층까지 빠르게 채우는 딥 토너", descJp: "低分子ヒアルロン酸が角質層まですばやく満たすディープトナー", descEn: "A deep toner with low-molecular hyaluronic acid that fills the stratum corneum fast.", fullMl: 200, price: 15100, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("더랩바이블랑두 올리고 히알루론산 저분자 딥 토너"), linkType: "search", image: "/assets/products/blancdoux-oligo-toner.webp" },
  { id: "bringgreen-teatree-toner", brand: "브링그린", brandJp: "ブリングリーン", brandEn: "Bring Green", name: "티트리 시카 수딩 토너", nameJp: "ティーツリーシカ スージングトナー", nameEn: "Tea Tree Cica Soothing Toner", category: "토너", ingredients: ["티트리추출물", "병풀"], forTypes: ["지성", "민감", "복합"], concerns: ["트러블"], rating: 4.53, feel: "진정", desc: "티트리와 시카로 트러블 피부를 순하게 진정시키는 토너", descJp: "ティーツリーとシカでトラブル肌をやさしく鎮静させるトナー", descEn: "Tea tree and cica gently calm troubled skin.", fullMl: 500, price: 27000, safety: ["무알코올", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189181", linkType: "direct", image: "/assets/products/bringgreen-teatree-toner.webp" },
  { id: "manyo-pantheto-toner", brand: "마녀공장", brandJp: "マニョファクトリー", brandEn: "Manyo Factory", name: "판테토인 에센스 토너", nameJp: "パンテトインエッセンストナー", nameEn: "Pantethine Essence Toner", category: "토너", ingredients: ["판테토인", "병풀"], forTypes: ["건성", "복합", "민감"], concerns: ["수분"], rating: 4.68, feel: "촉촉", desc: "판테토인 성분으로 빠르고 깊은 속보습을 채우는 에센스 토너", descJp: "パンテトイン成分ですばやく深い潤いを満たすエッセンストナー", descEn: "An essence toner with pantethine for fast, deep hydration.", fullMl: 200, price: 32000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000199405", linkType: "direct", image: "/assets/products/manyo-pantheto-toner.webp" },
  { id: "easydew-melatoning-toner", brand: "이지듀", brandJp: "イージーデュー", brandEn: "Easydew", name: "멜라토닝 울트라카밍 토너 시카알로에", nameJp: "メラトニング ウルトラカーミングトナー シカ&アロエ", nameEn: "Melatoning Ultra Calming Toner Cica & Aloe", category: "토너", ingredients: ["시카", "알로에"], forTypes: ["민감", "복합"], concerns: ["트러블", "기미"], rating: 4.4, feel: "진정", desc: "시카·알로에가 피부 열감과 자극을 빠르게 진정시키는 토너", descJp: "シカ・アロエが肌のほてりと刺激をすばやく鎮静させるトナー", descEn: "Cica and aloe quickly soothe heat and irritation.", fullMl: 130, price: 31800, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("이지듀 멜라토닝 울트라카밍 토너 시카알로에"), linkType: "search", image: "/assets/products/easydew-melatoning-toner.png" },
  { id: "roundlab-birch-toner", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "자작나무 수분 토너", nameJp: "白樺水分トナー", nameEn: "Birch Juice Moisture Toner", category: "토너", ingredients: ["자작나무수액", "히알루론산"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.39, feel: "촉촉", desc: "자작나무 수액이 촉촉하게 채워주는 수분 앰플 토너", descJp: "白樺樹液がしっとり満たす保湿アンプルトナー", descEn: "A hydrating ampoule toner with moisturizing birch sap.", fullMl: 300, price: 23800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000148252", linkType: "direct", image: "/assets/products/roundlab-birch-toner.webp" },
  { id: "fation-noscarnine-toner", brand: "파티온", brandJp: "パティオン", brandEn: "Fation", name: "노스카나인 트러블 클리어 토너", nameJp: "ノスカルニン トラブルクリアトナー", nameEn: "Noscarnine Trouble Clear Toner", category: "토너", ingredients: ["노스카나인", "알란토인"], forTypes: ["지성", "민감"], concerns: ["트러블"], rating: 4.4, feel: "산뜻", desc: "살리실산 유도체로 트러블 피부를 진정시키는 약산성 토너", descJp: "サリチル酸誘導体でトラブル肌を鎮静させる弱酸性トナー", descEn: "A weakly-acidic toner with a salicylic acid derivative to calm troubled skin.", fullMl: 200, price: 19900, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000182787", linkType: "direct", image: "/assets/products/fation-noscarnine-toner.webp" },
  { id: "ahc-herb-lemon-toner", brand: "AHC", brandJp: "AHC", brandEn: "AHC", name: "허브솔루션 레몬 토너", nameJp: "ハーブソリューション レモントナー", nameEn: "Herb Solution Lemon Toner", category: "토너", ingredients: ["레몬추출물"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.2, feel: "산뜻", desc: "상큼한 레몬 향으로 피지와 유분을 산뜻하게 정돈하는 토너", descJp: "爽やかなレモンの香りで皮脂と油分をさっぱり整えるトナー", descEn: "A refreshing lemon-scented toner that refines sebum and oiliness.", fullMl: 500, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165366", linkType: "direct", image: "/assets/products/ahc-herb-lemon-toner.webp" },
  { id: "scinic-hyaluronic-skin", brand: "싸이닉", brandJp: "サイニック", brandEn: "Scinic", name: "히아루론산 앰플 스킨", nameJp: "ヒアルロン酸アンプル化粧水", nameEn: "Hyaluronic Acid Ampoule Skin", category: "토너", ingredients: ["히알루론산", "마데카소사이드"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.4, feel: "촉촉", desc: "5중 히알루론산이 촘촘하게 채우는 순한 수분 앰플 스킨", descJp: "5種のヒアルロン酸がきめ細かく満たすやさしい保湿アンプル化粧水", descEn: "A gentle hydrating ampoule toner with 5 types of hyaluronic acid.", fullMl: 150, price: 18000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("싸이닉 히아루론산 앰플 스킨"), linkType: "search", image: "/assets/products/scinic-hyaluronic-skin.jpg" },
  { id: "numbuzin-no5-glutathione", brand: "넘버즈인", brandJp: "ナンバーズイン", brandEn: "Numbuzin", name: "5번 글루타치온C 흔적 앰플", nameJp: "5番 グルタチオンC 跡ケアアンプル", nameEn: "No.5 Glutathione C Marks Ampoule", category: "앰플", ingredients: ["글루타치온", "비타민C", "트라넥삼산", "나이아신아마이드"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["기미"], rating: 4.6, feel: "산뜻", desc: "글루타치온·비타민C·트라넥삼산으로 흔적·잡티를 밝혀주는 브라이트닝 앰플", descJp: "グルタチオン・ビタミンC・トラネキサム酸で跡・シミを明るくするブライトニングアンプル", descEn: "A brightening ampoule with glutathione, vitamin C, and tranexamic acid for marks and spots.", fullMl: 30, price: 28000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("넘버즈인 5번 글루타치온C 흔적 앰플"), linkType: "search", image: "/assets/products/numbuzin-no5-glutathione.jpeg" },
  { id: "missha-vitac-plus-ampoule", brand: "미샤", brandJp: "ミシャ", brandEn: "Missha", name: "비타씨플러스 잡티씨 탄력 앰플", nameJp: "ビタCプラス シミCハリアンプル", nameEn: "Vita-C Plus Blemish-C Firming Ampoule", category: "앰플", ingredients: ["비타민C", "나이아신아마이드", "아데노신", "프로폴리스"], forTypes: ["건성", "지성", "복합", "중성"], concerns: ["기미", "주름"], rating: 4.6, feel: "산뜻", desc: "비타민C·나이아신아마이드로 잡티를 밝히고 탄력까지 잡는 이중기능성 앰플", descJp: "ビタミンC・ナイアシンアミドでシミを明るくし弾力まで叶えるデュアル機能性アンプル", descEn: "A dual-function ampoule with vitamin C and niacinamide for brightness and firmness.", fullMl: 40, price: 28000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 비타씨플러스 잡티씨 탄력 앰플"), linkType: "search", image: "/assets/products/missha-vitac-plus-ampoule.jpeg" },
  { id: "missha-time-revolution-night-repair", brand: "미샤", brandJp: "ミシャ", brandEn: "Missha", name: "타임 레볼루션 나이트 리페어 보랏빛 앰플 5X", nameJp: "タイムレボリューション ナイトリペアアンプル5X", nameEn: "Time Revolution Night Repair Ampoule 5X", category: "앰플", ingredients: ["비피다발효용해물", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["주름", "수분", "기미"], rating: 4.7, feel: "촉촉", desc: "비피다 발효 성분으로 밤사이 피부를 재생·보습하는 나이트 리페어 앰플", descJp: "ビフィズス発酵成分で夜の間に肌を再生・保湿するナイトリペアアンプル", descEn: "A night repair ampoule with bifida ferment to regenerate and hydrate overnight.", fullMl: 70, price: 36000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 타임 레볼루션 나이트 리페어 보랏빛 앰플 5X"), linkType: "search", image: "/assets/products/missha-time-revolution-night-repair.jpeg" },
  { id: "missha-bee-pollen-ampouler", brand: "미샤", brandJp: "ミシャ", brandEn: "Missha", name: "비폴렌 리뉴 앰풀러", nameJp: "ビーポーレン リニューアンプラー", nameEn: "Bee Pollen Renew Ampouler", category: "앰플", ingredients: ["화분추출물", "프로폴리스", "꿀추출물", "판테놀"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "트러블", "주름"], rating: 4.6, feel: "진정", desc: "비폴렌·프로폴리스로 피부를 진정하고 밀도를 채우는 항산화 앰플", descJp: "ビーポーレン・プロポリスで肌を鎮静し密度を満たす抗酸化アンプル", descEn: "An antioxidant ampoule with bee pollen and propolis to soothe and plump skin.", fullMl: 40, price: 28000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 비폴렌 리뉴 앰풀러"), linkType: "search", image: "/assets/products/missha-bee-pollen-ampouler.png" },
  { id: "goodal-vitac15-ampoule", brand: "구달", brandJp: "グーダル", brandEn: "Goodal", name: "청귤 비타C 15 잡티 케어 앰플", nameJp: "青みかんビタミンC15 シミケアアンプル", nameEn: "Green Tangerine Vitamin C 15 Blemish Care Ampoule", category: "앰플", ingredients: ["비타민C", "청귤추출물", "나이아신아마이드", "글루타치온"], forTypes: ["건성", "지성", "복합", "중성"], concerns: ["기미"], rating: 4.4, feel: "산뜻", desc: "순수 비타민C 15%·청귤추출물로 기미·잡티를 집중 케어하는 브라이트닝 앰플", descJp: "純粋ビタミンC15%・青みかん抽出物でシミ・くすみを集中ケアするブライトニングアンプル", descEn: "A brightening ampoule with 15% pure vitamin C and citrus extract for spots and dullness.", fullMl: 16, price: 32000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("구달 청귤 비타C 15 잡티 케어 앰플"), linkType: "search", image: "/assets/products/goodal-vitac15-ampoule.jpeg" },
  { id: "manyo-bifida-biome-ampoule", brand: "마녀공장", brandJp: "マニョファクトリー", brandEn: "Manyo Factory", name: "비피다 바이옴 콤플렉스 앰플", nameJp: "ビフィズスバイオームコンプレックスアンプル", nameEn: "Bifida Biome Complex Ampoule", category: "앰플", ingredients: ["비피다발효용해물", "나이아신아마이드", "히알루론산", "아데노신"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분", "주름", "기미"], rating: 4.7, feel: "촉촉", desc: "비피다 발효 성분으로 장벽을 강화하고 미백·주름까지 돕는 촉촉한 앰플", descJp: "ビフィズス発酵成分でバリアを強化し美白・シワまでケアするしっとりアンプル", descEn: "A hydrating ampoule with bifida ferment to strengthen the barrier and help with brightness and wrinkles.", fullMl: 30, price: 23000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 비피다 바이옴 콤플렉스 앰플"), linkType: "search", image: "/assets/products/manyo-bifida-biome-ampoule.jpeg" },
  { id: "easydew-egf-melatoning-ampoule", brand: "이지듀", brandJp: "イージーデュー", brandEn: "Easydew", name: "DW-EGF 멜라토닝 원데이 앰플", nameJp: "DW-EGF メラトニングワンデーアンプル", nameEn: "DW-EGF Melatoning One-Day Ampoule", category: "앰플", ingredients: ["EGF", "나이아신아마이드", "글루타치온", "아스코르빌글루코사이드"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "DW-EGF와 나이아신아마이드·글루타치온으로 미백·탄력을 케어하는 더마 앰플", descJp: "DW-EGFとナイアシンアミド・グルタチオンで美白・弾力をケアするダーマアンプル", descEn: "A derma ampoule with DW-EGF, niacinamide, and glutathione for brightness and firmness.", fullMl: 30, price: 39000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("이지듀 DW-EGF 멜라토닝 원데이 앰플"), linkType: "search", image: "/assets/products/easydew-egf-melatoning-ampoule.jpeg" },
  { id: "centellian24-madeca-power-ampoule", brand: "센텔리안24", brandJp: "センテリアン24", brandEn: "Centellian24", name: "마데카 파워 앰플", nameJp: "マデカパワーアンプル", nameEn: "Madeca Power Ampoule", category: "앰플", ingredients: ["병풀추출물", "마데카소사이드", "나이아신아마이드", "아데노신"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["주름", "기미", "트러블"], rating: 4.5, feel: "진정", desc: "병풀 유효성분에 나이아신아마이드·아데노신을 더해 진정과 미백·주름을 잡는 이중기능성 앰플", descJp: "ツボクサ有効成分にナイアシンアミド・アデノシンを加え鎮静と美白・シワを叶えるデュアル機能性アンプル", descEn: "A dual-function ampoule with centella actives plus niacinamide and adenosine for soothing, brightness, and wrinkles.", fullMl: 30, price: 29800, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("센텔리안24 마데카 파워 앰플"), linkType: "search", image: "/assets/products/centellian24-madeca-power-ampoule.png" },
  { id: "mediheal-madecassoside-serum", brand: "메디힐", brandJp: "メディヒール", brandEn: "Mediheal", name: "마데카소사이드 흔적 리페어 세럼", nameJp: "マデカソサイド 跡リペアセラム", nameEn: "Madecassoside Marks Repair Serum", category: "세럼", ingredients: ["마데카소사이드", "병풀추출물", "판테놀", "히알루론산"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["트러블", "수분", "기미"], rating: 4.3, feel: "진정", desc: "마데카소사이드가 붉은 흔적을 진정시키고 수분을 채워 결·톤을 정돈하는 세럼", descJp: "マデカソサイドが赤み跡を鎮静させ潤いを満たし肌理・トーンを整えるセラム", descEn: "A serum with madecassoside that soothes redness marks and hydrates to refine texture and tone.", fullMl: 40, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 마데카소사이드 흔적 리페어 세럼"), linkType: "search", image: "/assets/products/mediheal-madecassoside-serum.jpeg" },
  { id: "drg-red-blemish-hyalcica-serum", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "레드 블레미쉬 클리어 히알 시카 수딩 세럼", nameJp: "レッドブレミッシュ クリアヒアルシカスージングセラム", nameEn: "Red Blemish Clear Hyal-Cica Soothing Serum", category: "세럼", ingredients: ["병풀추출물", "히알루론산", "판테놀", "마데카소사이드", "알란토인"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "트러블"], rating: 4.7, feel: "진정", desc: "'히알시카'로 민감 피부에 수분을 채우고 자극·흔적을 진정시키는 수분 진정 세럼", descJp: "「ヒアルシカ」で敏感肌に潤いを満たし刺激・跡を鎮静させる保湿鎮静セラム", descEn: "A hydrating, soothing serum with \"Hyal-Cica\" that hydrates sensitive skin and calms irritation and marks.", fullMl: 50, price: 33000, safety: ["저자극", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 클리어 히알 시카 수딩 세럼"), linkType: "search", image: "/assets/products/drg-red-blemish-hyalcica-serum.jpeg" },
  { id: "drg-brightening-up-sun", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "브라이트닝 업 선 플러스", nameJp: "ブライトニングアップサンプラス", nameEn: "Brightening Up Sun Plus", category: "선크림", ingredients: ["징크옥사이드", "티타늄디옥사이드", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "산뜻", desc: "SPF50+ 피치베이지 톤업 선크림, 화사한 톤보정과 파데프리 마무리", descJp: "SPF50+ ピーチベージュトーンアップ日焼け止め、華やかなトーン補正でファンデ要らずの仕上がり", descEn: "SPF50+ peach-beige tone-up sunscreen for a radiant tone and makeup-free finish.", fullMl: 50, price: 32000, safety: ["미백기능성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 브라이트닝 업 선 플러스"), linkType: "search", image: "/assets/products/drg-brightening-up-sun.jpg" },
  { id: "mediheal-madecassoside-sun-serum", brand: "메디힐", brandJp: "メディヒール", brandEn: "Mediheal", name: "마데카소사이드 수분 선세럼 흔적 리페어", nameJp: "マデカソサイド 保湿サンセラム跡リペア", nameEn: "Madecassoside Moisture Sun Serum Marks Repair", category: "선크림", ingredients: ["나이아신아마이드", "마데카소사이드", "병풀추출물", "히알루론산"], forTypes: ["건성", "민감", "복합"], concerns: ["트러블", "수분", "기미"], rating: 4.6, feel: "촉촉", desc: "SPF50+ 세럼형 선케어, 마데카소사이드로 진정·흔적 케어와 수분을 동시에", descJp: "SPF50+ セラムタイプ日焼け止め、マデカソサイドで鎮静・跡ケアと保湿を同時に", descEn: "SPF50+ serum-type sun care with madecassoside for soothing, mark care, and hydration at once.", fullMl: 50, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 마데카소사이드 수분 선세럼 흔적 리페어"), linkType: "search", image: "/assets/products/mediheal-madecassoside-sun-serum.jpeg" },
  { id: "athe-vegan-relief-sun", brand: "아떼", brandJp: "アテ", brandEn: "Athe", name: "비건 릴리프 무기자차 선크림", nameJp: "ヴィーガンリリーフ ノンケミカル日焼け止め", nameEn: "Vegan Relief Mineral Sun Cream", category: "선크림", ingredients: ["징크옥사이드", "티타늄디옥사이드", "병풀추출물", "판테놀"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분"], rating: 4.5, feel: "진정", desc: "SPF50+ 비건 무기자차 선크림, 민감 피부 진정과 자연스러운 톤보정", descJp: "SPF50+ ヴィーガンノンケミカル日焼け止め、敏感肌の鎮静と自然なトーン補正", descEn: "SPF50+ vegan mineral sunscreen that soothes sensitive skin with a natural tone-up.", fullMl: 50, price: 34000, safety: ["무기자차", "비건", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아떼 비건 릴리프 무기자차 선크림"), linkType: "search", image: "/assets/products/athe-vegan-relief-sun.png" },
  { id: "daeffect-hydro-sunscreen", brand: "디에이이펙트", brandJp: "ディーエーイフェクト", brandEn: "D.A Effect", name: "하이드로 선스크린", nameJp: "ハイドロサンスクリーン", nameEn: "Hydro Sunscreen", category: "선크림", ingredients: ["병풀추출물", "세라마이드", "나이아신아마이드", "판테놀"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분", "주름"], rating: 4.6, feel: "촉촉", desc: "SPF50+ 더마 선크림, 시술 후에도 순한 진정·보습과 백탁 없는 밀착 마무리", descJp: "SPF50+ ダーマ日焼け止め、施術後にもやさしい鎮静・保湿と白浮きしない密着仕上がり", descEn: "SPF50+ derma sunscreen with gentle soothing, hydration, and a no-white-cast finish, even post-procedure.", fullMl: 30, price: 39000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("디에이이펙트 하이드로 선스크린"), linkType: "search", image: "/assets/products/daeffect-hydro-sunscreen.jpeg" },
  { id: "biozin-albumin-mela-toneup-sun", brand: "비오진", brandJp: "ビオジン", brandEn: "Biozin", name: "알부민 멜라 리셋 톤업 선크림", nameJp: "アルブミン メラリセットトーンアップ日焼け止め", nameEn: "Albumin Mela Reset Tone-Up Sun Cream", category: "선크림", ingredients: ["티타늄디옥사이드", "나이아신아마이드", "트라넥삼산", "알부민추출물"], forTypes: ["복합", "건성", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 톤업 선크림, 알부민·트라넥삼산으로 멜라닌 케어와 화사한 톤업", descJp: "SPF50+ トーンアップ日焼け止め、アルブミン・トラネキサム酸でメラニンケアと華やかなトーンアップ", descEn: "SPF50+ tone-up sunscreen with albumin and tranexamic acid for melanin care and a radiant glow.", fullMl: 50, price: 35000, safety: ["미백기능성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("비오진 알부민 멜라 리셋 톤업 선크림"), linkType: "search", image: "/assets/products/biozin-albumin-mela-toneup-sun.jpg" },
  { id: "scinic-enjoy-mild-sun-essence", brand: "싸이닉", brandJp: "サイニック", brandEn: "Scinic", name: "엔조이 슈퍼 마일드 수분 선에센스", nameJp: "エンジョイスーパーマイルド保湿サンエッセンス", nameEn: "Enjoy Super Mild Moisture Sun Essence", category: "선크림", ingredients: ["에칠헥실메톡시신나메이트", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "복합", "민감"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 유기자차 선에센스, 수분 에센스처럼 촉촉하게 흡수되는 데일리 자차", descJp: "SPF50+ 有機系日焼け止めエッセンス、保湿エッセンスのようにしっとり馴染むデイリーUV", descEn: "SPF50+ organic sunscreen essence that absorbs like a hydrating essence for daily wear.", fullMl: 50, price: 15000, safety: ["저자극테스트", "비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("싸이닉 엔조이 슈퍼 마일드 수분 선에센스"), linkType: "search", image: "/assets/products/scinic-enjoy-mild-sun-essence.jpg" },
  { id: "hieut-vita-waterful-sun-essence", brand: "hieut", brandJp: "ヒウッ", brandEn: "hieut", name: "비타 워터풀 선에센스", nameJp: "ビタウォーターフルサンエッセンス", nameEn: "Vita Waterful Sun Essence", category: "선크림", ingredients: ["나이아신아마이드", "히알루론산"], forTypes: ["건성", "복합", "중성"], concerns: ["수분"], rating: 4.4, feel: "촉촉", desc: "SPF50+ PA++++ 워터풀 선에센스, 산뜻하게 흡수되는 수분 자차", descJp: "SPF50+ PA++++ ウォーターフル日焼け止めエッセンス、さっぱり馴染む保湿UV", descEn: "SPF50+ PA++++ waterful sun essence that absorbs refreshingly.", fullMl: 50, price: 22000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("hieut 비타 워터풀 선에센스"), linkType: "search", image: "/assets/products/hieut-vita-waterful-sun-essence.jpg" },
  { id: "ahc-masters-toneup-sun-serum", brand: "AHC", brandJp: "AHC", brandEn: "AHC", name: "마스터즈 톤업 선세럼", nameJp: "マスターズトーンアップサンセラム", nameEn: "Master's Tone-Up Sun Serum", category: "선크림", ingredients: ["티타늄디옥사이드", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "복합", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 세럼형 톤업 선크림, 백탁 없이 자연스러운 데일리 톤업", descJp: "SPF50+ セラムタイプトーンアップ日焼け止め、白浮きなく自然なデイリートーンアップ", descEn: "SPF50+ serum-type tone-up sunscreen for a natural daily glow with no white cast.", fullMl: 50, price: 33000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("AHC 마스터즈 톤업 선세럼"), linkType: "search", image: "/assets/products/ahc-masters-toneup-sun-serum.jpg" },
  { id: "shingmulnara-watery-sun-gel", brand: "식물나라", brandJp: "シンムルラダ", brandEn: "Shingmulnara", name: "가벼운 수분 선 젤", nameJp: "軽い保湿サンジェル", nameEn: "Light Moisture Sun Gel", category: "선크림", ingredients: ["나이아신아마이드", "알로에베라잎추출물", "히알루론산", "아데노신"], forTypes: ["지성", "복합"], concerns: ["수분"], rating: 4.4, feel: "산뜻", desc: "SPF50+ 수분 젤 선크림, 백탁 없이 산뜻하게 발리는 가벼운 데일리 자차", descJp: "SPF50+ 保湿ジェル日焼け止め、白浮きなくさっぱり伸びる軽いデイリーUV", descEn: "SPF50+ watery gel sunscreen, light and refreshing with no white cast.", fullMl: 60, price: 14800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("식물나라 가벼운 수분 선 젤 선크림"), linkType: "search", image: "/assets/products/shingmulnara-watery-sun-gel.jpg" },
  { id: "cellfusionc-spot-toning-sunscreen", brand: "셀퓨전씨", brandJp: "セルフュージョンシー", brandEn: "Cellfusion C", name: "잡티 토닝 썬스크린", nameJp: "シミトーニングサンスクリーン", nameEn: "Blemish Toning Sunscreen", category: "선크림", ingredients: ["티타늄디옥사이드", "징크옥사이드", "나이아신아마이드", "아데노신"], forTypes: ["지성", "복합", "민감"], concerns: ["기미"], rating: 4.5, feel: "산뜻", desc: "SPF50+ 무기자차 톤업 선크림, 잡티 케어까지 챙기는 미백·주름 기능성", descJp: "SPF50+ ノンケミカルトーンアップ日焼け止め、シミケアまで叶える美白・シワ機能性", descEn: "SPF50+ mineral tone-up sunscreen with brightening and anti-wrinkle care for spots.", fullMl: 50, price: 27900, safety: ["무기자차", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("셀퓨전씨 잡티 토닝 썬스크린"), linkType: "search", image: "/assets/products/cellfusionc-spot-toning-sunscreen.jpeg" },
  { id: "goodal-houttuynia-calming-sun", brand: "구달", brandJp: "グーダル", brandEn: "Goodal", name: "맑은 어성초 진정 무기자차 선크림", nameJp: "澄んだドクダミ鎮静ノンケミカル日焼け止め", nameEn: "Clear Heartleaf Calming Mineral Sun Cream", category: "선크림", ingredients: ["어성초추출물", "징크옥사이드", "티타늄디옥사이드", "판테놀"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블", "수분"], rating: 4.5, feel: "진정", desc: "SPF50+ 어성초 진정 무기자차 선크림, 백탁 적고 자극받은 피부를 진정", descJp: "SPF50+ ドクダミ鎮静ノンケミカル日焼け止め、白浮きが少なく刺激を受けた肌を鎮静", descEn: "SPF50+ houttuynia soothing mineral sunscreen with minimal white cast for irritated skin.", fullMl: 50, price: 20000, safety: ["무기자차", "비건", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("구달 맑은 어성초 진정 무기자차 선크림"), linkType: "search", image: "/assets/products/goodal-houttuynia-calming-sun.jpeg" },
  { id: "roundlab-birch-cleanser", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "자작나무 수분 클렌저", nameJp: "白樺水分クレンザー", nameEn: "Birch Juice Moisture Cleanser", category: "클렌징", ingredients: ["자작나무수", "히알루론산", "판테놀"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분"], rating: 4.6, feel: "촉촉", desc: "자작나무수 함유 약산성 클렌저, 당김 없이 수분감 있게 마무리", descJp: "白樺水配合の弱酸性クレンザー、つっぱらずしっとりとした仕上がり", descEn: "A weakly-acidic cleanser with birch water for a hydrated, non-tight finish.", fullMl: 150, price: 15000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 자작나무 수분 클렌저"), linkType: "search", image: "/assets/products/roundlab-birch-cleanser.jpg" },
  { id: "offon-7xcica-biome-foam", brand: "오프온", brandJp: "オフオン", brandEn: "Offon", name: "7X 시카 바이옴 약산성 클렌징폼", nameJp: "7X シカバイオーム弱酸性洗顔フォーム", nameEn: "7X Cica Biome pH-Balanced Cleansing Foam", category: "클렌징", ingredients: ["병풀추출물", "바이옴", "판테놀", "티트리오일"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.5, feel: "진정", desc: "시카·바이옴 약산성 클렌징폼, 트러블 진정과 순한 세정", descJp: "シカ・バイオーム弱酸性洗顔フォーム、トラブル鎮静とやさしい洗浄", descEn: "A weakly-acidic cica and biome foam cleanser for gentle cleansing and troubled-skin care.", fullMl: 120, price: 23000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("오프온 7X 시카 바이옴 약산성 클렌징폼"), linkType: "search", image: "/assets/products/offon-7xcica-biome-foam.png" },
  { id: "roundlab-pine-cica-cleanser", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "소나무 진정 시카 클렌저", nameJp: "松鎮静シカクレンザー", nameEn: "Pine Calming Cica Cleanser", category: "클렌징", ingredients: ["소나무잎추출물", "병풀추출물", "마데카소사이드", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "소나무잎·시카 폼 클렌저, 피지 세정과 자극받은 피부 진정", descJp: "松葉・シカ泡クレンザー、皮脂洗浄と刺激を受けた肌の鎮静", descEn: "A pine needle and cica foam cleanser for sebum cleansing and soothing irritated skin.", fullMl: 150, price: 17000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 소나무 진정 시카 클렌저"), linkType: "search", image: "/assets/products/roundlab-pine-cica-cleanser.jpeg" },
  { id: "roundlab-dokdo-bubble-foam", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "1025 독도 버블 클렌징 폼", nameJp: "1025独島バブル洗顔フォーム", nameEn: "1025 Dokdo Bubble Cleansing Foam", category: "클렌징", ingredients: ["해수", "병풀잎추출물", "소나무잎추출물", "히알루론산", "판테놀"], forTypes: ["지성", "복합", "중성", "민감"], concerns: ["트러블"], rating: 4.5, feel: "산뜻", desc: "해수·병풀 함유 약산성 버블 폼, 풍성한 거품으로 산뜻하게 세정", descJp: "海水・ツボクサ配合の弱酸性バブルフォーム、豊かな泡でさっぱり洗浄", descEn: "A weakly-acidic bubble foam with seawater and centella for a rich, refreshing cleanse.", fullMl: 150, price: 13000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 1025 독도 버블 클렌징 폼"), linkType: "search", image: "/assets/products/roundlab-dokdo-bubble-foam.jpeg" },
  { id: "mediheal-derma-cream-cleanser-madeca", brand: "메디힐", brandJp: "メディヒール", brandEn: "Mediheal", name: "더마 크림 팩 클렌저 마데카소사이드", nameJp: "ダーマクリームパッククレンザー マデカソサイド", nameEn: "Derma Cream Pack Cleanser Madecassoside", category: "클렌징", ingredients: ["마데카소사이드", "병풀잎추출물", "판테놀", "나이아신아마이드"], forTypes: ["건성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.4, feel: "촉촉", desc: "마데카소사이드 크림형 팩 클렌저, 세정과 함께 진정·장벽 보습", descJp: "マデカソサイドクリームタイプパッククレンザー、洗浄と共に鎮静・バリア保湿", descEn: "A madecassoside cream-type pack cleanser for cleansing plus soothing and barrier hydration.", fullMl: 120, price: 21000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 더마 크림 팩 클렌저 마데카소사이드"), linkType: "search", image: "/assets/products/mediheal-derma-cream-cleanser-madeca.jpeg" },
  { id: "mediheal-derma-cream-cleanser-pdrn", brand: "메디힐", brandJp: "メディヒール", brandEn: "Mediheal", name: "더마 크림 팩 클렌저 피디알엔", nameJp: "ダーマクリームパッククレンザー PDRN", nameEn: "Derma Cream Pack Cleanser PDRN", category: "클렌징", ingredients: ["PDRN", "히알루론산", "글리세린", "장미꽃추출물"], forTypes: ["건성", "복합", "민감"], concerns: ["주름", "수분"], rating: 4.6, feel: "촉촉", desc: "PDRN 함유 쫀득한 크림형 팩 클렌저, 모공 세정과 탄력 케어", descJp: "PDRN配合の弾力あるクリームタイプパッククレンザー、毛穴洗浄と弾力ケア", descEn: "A springy, PDRN-infused cream-type pack cleanser for pore cleansing and firmness care.", fullMl: 120, price: 21000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 더마 크림 팩 클렌저 피디알엔"), linkType: "search", image: "/assets/products/mediheal-derma-cream-cleanser-pdrn.jpeg" },
  { id: "abib-acne-heartleaf-foam", brand: "아비브", brandJp: "アビブ", brandEn: "Abib", name: "아크네 폼 클렌저 어성초 폼", nameJp: "アクネフォームクレンザー ドクダミフォーム", nameEn: "Acne Foam Cleanser Heartleaf Foam", category: "클렌징", ingredients: ["어성초추출물", "살리실산(BHA)", "병풀추출물"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "어성초·살리실산 약산성 폼, 트러블 진정과 피지·모공 케어", descJp: "ドクダミ・サリチル酸弱酸性フォーム、トラブル鎮静と皮脂・毛穴ケア", descEn: "A weakly-acidic foam with heartleaf and salicylic acid for troubled skin, sebum, and pore care.", fullMl: 150, price: 16000, safety: ["약산성", "저자극", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 아크네 폼 클렌저 어성초 폼"), linkType: "search", image: "/assets/products/abib-acne-heartleaf-foam.png" },
  { id: "aboutme-rice-makgeolli-foam", brand: "어바웃미", brandJp: "アバウトミー", brandEn: "About Me", name: "쌀 막걸리 클렌징 폼", nameJp: "米マッコリ洗顔フォーム", nameEn: "Rice Makgeolli Cleansing Foam", category: "클렌징", ingredients: ["쌀겨수", "쌀추출물", "갈락토미세스발효여과물", "글리세린"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "기미"], rating: 4.6, feel: "촉촉", desc: "쌀겨수·쌀 발효 성분의 쫀쫀한 거품 약산성 폼, 보습 세안과 톤 케어", descJp: "米ぬか水・米発酵成分の弾力ある泡の弱酸性フォーム、保湿洗顔とトーンケア", descEn: "A bouncy, weakly-acidic foam with rice bran water and rice ferment for hydrating cleanse and tone care.", fullMl: 120, price: 14000, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("어바웃미 쌀 막걸리 클렌징 폼"), linkType: "search", image: "/assets/products/aboutme-rice-makgeolli-foam.jpeg" },
  { id: "centellian24-madeca-amino-cleanser", brand: "센텔리안24", brandJp: "センテリアン24", brandEn: "Centellian24", name: "마데카 아미노산 클렌징폼", nameJp: "マデカアミノ酸洗顔フォーム", nameEn: "Madeca Amino Acid Cleansing Foam", category: "클렌징", ingredients: ["병풀추출물", "마데카소사이드", "아미노산계면활성제", "판테놀"], forTypes: ["건성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.5, feel: "촉촉", desc: "마데카소사이드·아미노산 계면활성제의 약산성 저자극 폼, 진정·보습 세안", descJp: "マデカソサイド・アミノ酸系界面活性剤の弱酸性低刺激フォーム、鎮静・保湿洗顔", descEn: "A weakly-acidic, low-irritation foam with madecassoside and amino acid surfactants for soothing, hydrating cleanse.", fullMl: 160, price: 18000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("센텔리안24 마데카 아미노산 클렌징폼"), linkType: "search", image: "/assets/products/centellian24-madeca-amino-cleanser.png" },
  { id: "cellfusionc-pore-sun-cleanser", brand: "셀퓨전씨", brandJp: "セルフュージョンシー", brandEn: "Cellfusion C", name: "포어 썬 클렌징 폼", nameJp: "ポアサン洗顔フォーム", nameEn: "Pore Sun Cleansing Foam", category: "클렌징", ingredients: ["유칼립투스잎추출물", "살리실산(BHA)", "히알루론산"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.5, feel: "산뜻", desc: "살리실산·유칼립투스 모공 딥클렌징 폼, 선크림·피지 세정에 특화", descJp: "サリチル酸・ユーカリ毛穴ディープクレンジングフォーム、日焼け止め・皮脂洗浄に特化", descEn: "A deep pore-cleansing foam with salicylic acid and eucalyptus, made for removing sunscreen and sebum.", fullMl: 150, price: 18000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("셀퓨전씨 포어 썬 클렌징 폼"), linkType: "search", image: "/assets/products/cellfusionc-pore-sun-cleanser.jpeg" },
  { id: "abib-collagen-gel-mask", brand: "아비브", brandJp: "アビブ", brandEn: "Abib", name: "콜라겐 겔 마스크 수분초 젤리", nameJp: "コラーゲンジェルマスク 保湿ゼリー", nameEn: "Collagen Gel Mask Moisture Jelly", category: "마스크팩", ingredients: ["콜라겐", "히알루론산", "판테놀", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["수분", "주름"], rating: 4.7, feel: "촉촉", desc: "콜라겐·히알루론산 겔 시트, 수분과 탄력을 함께 채우는 밀착 마스크", descJp: "コラーゲン・ヒアルロン酸ジェルシート、潤いと弾力を同時に満たす密着マスク", descEn: "A close-fitting collagen and hyaluronic acid gel sheet that fills in hydration and firmness together.", fullMl: 30, price: 5000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 콜라겐 겔 마스크 수분초 젤리"), linkType: "search", image: "/assets/products/abib-collagen-gel-mask.jpg" },
  { id: "abib-heartleaf-sheet-mask", brand: "아비브", brandJp: "アビブ", brandEn: "Abib", name: "약산성 pH 시트 마스크 어성초 핏", nameJp: "弱酸性pHシートマスク ドクダミフィット", nameEn: "pH-Balanced Sheet Mask Heartleaf Fit", category: "마스크팩", ingredients: ["어성초추출물", "판테놀", "히알루론산", "글리세린"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "어성초 담은 약산성 투명 시트, 민감·트러블 피부를 진정시키는 데일리 마스크", descJp: "ドクダミを配合した弱酸性透明シート、敏感・トラブル肌を鎮静させるデイリーマスク", descEn: "A weakly-acidic, clear sheet with heartleaf for daily soothing of sensitive, troubled skin.", fullMl: 30, price: 4000, safety: ["약산성", "저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 약산성 pH 시트 마스크 어성초 핏"), linkType: "search", image: "/assets/products/abib-heartleaf-sheet-mask.jpg" },
  { id: "firstlab-probiotic-mask", brand: "퍼스트랩", brandJp: "ファーストラボ", brandEn: "First Lab", name: "프로바이오틱 마스크", nameJp: "プロバイオティックマスク", nameEn: "Probiotic Mask", category: "마스크팩", ingredients: ["유산균발효여과물", "나이아신아마이드", "글루타치온", "펩타이드"], forTypes: ["민감", "복합", "중성"], concerns: ["트러블", "기미", "수분"], rating: 4.5, feel: "진정", desc: "유산균·나이아신아마이드로 장벽 진정과 브라이트닝을 돕는 시트 마스크", descJp: "乳酸菌・ナイアシンアミドでバリア鎮静とブライトニングを助けるシートマスク", descEn: "A sheet mask with probiotics and niacinamide to help soothe the barrier and brighten.", fullMl: 25, price: 2000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("퍼스트랩 프로바이오틱 마스크"), linkType: "search", image: "/assets/products/firstlab-probiotic-mask.jpg" },
  { id: "dalba-vita-toning-niacinamide-mask", brand: "달바", brandJp: "ダルバ", brandEn: "d'Alba", name: "비타 토닝 나이아신아마이드 5% 마스크", nameJp: "ビタトーニング ナイアシンアミド5%マスク", nameEn: "Vita Toning Niacinamide 5% Mask", category: "마스크팩", ingredients: ["비타민나무수", "나이아신아마이드", "글루타치온", "히알루론산"], forTypes: ["중성", "복합", "건성"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "나이아신아마이드 5%·비타민나무수의 미백·주름 2중 기능성 톤업 시트 마스크", descJp: "ナイアシンアミド5%・ビタミンツリー水の美白・シワ2重機能性トーンアップシートマスク", descEn: "A dual-function tone-up sheet mask with 5% niacinamide and vitamin tree water for brightness and wrinkles.", fullMl: 28, price: 6000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 비타 토닝 나이아신아마이드 5% 마스크팩"), linkType: "search", image: "/assets/products/dalba-vita-toning-niacinamide-mask.jpg" },
  { id: "mediheal-dna-proatin-mask", brand: "메디힐", brandJp: "メディヒール", brandEn: "Mediheal", name: "디엔에이 프로아틴 마스크", nameJp: "DNAプロアチンマスク", nameEn: "DNA Proatin Mask", category: "마스크팩", ingredients: ["하이드롤라이즈드콜라겐", "세라마이드", "아세틸헥사펩타이드-8", "판테놀"], forTypes: ["건성", "중성", "복합"], concerns: ["수분", "주름"], rating: 4.4, feel: "촉촉", desc: "수분단백질·세라마이드로 속건조를 케어하고 탄력을 채우는 보습 시트 마스크", descJp: "保湿タンパク質・セラミドでインナードライをケアし弾力を満たす保湿シートマスク", descEn: "A hydrating sheet mask with moisture proteins and ceramide for inner dryness and firmness.", fullMl: 25, price: 3000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 디엔에이 프로아틴 마스크"), linkType: "search", image: "/assets/products/mediheal-dna-proatin-mask.jpg" },
  { id: "drg-red-blemish-soothing-mask", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "레드 블레미쉬 쿨 수딩 마스크", nameJp: "レッドブレミッシュ クールスージングマスク", nameEn: "Red Blemish Cool Soothing Mask", category: "마스크팩", ingredients: ["병풀추출물", "마데카소사이드", "판테놀", "히알루론산", "알란토인"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "시카 콤플렉스로 예민해진 피부를 진정시키는 수분 진정 시트 마스크", descJp: "シカコンプレックスで敏感になった肌を鎮静させる保湿鎮静シートマスク", descEn: "A hydrating, soothing sheet mask with cica complex for sensitized skin.", fullMl: 30, price: 4000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 쿨 수딩 마스크"), linkType: "search", image: "/assets/products/drg-red-blemish-soothing-mask.webp" },
  { id: "drg-blacksnail-lifting-mask", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "블랙스네일 리프팅 마스크", nameJp: "ブラックスネイルリフティングマスク", nameEn: "Black Snail Lifting Mask", category: "마스크팩", ingredients: ["달팽이점액여과물", "프로폴리스추출물", "히알루론산", "아데노신", "콜라겐"], forTypes: ["건성", "중성", "복합"], concerns: ["주름", "수분"], rating: 4.8, feel: "촉촉", desc: "블랙스네일·프로폴리스 영양 성분으로 탄력을 채우는 리프팅 시트 마스크", descJp: "ブラックスネイル・プロポリス栄養成分で弾力を満たすリフティングシートマスク", descEn: "A lifting sheet mask with black snail and propolis nutrients for firmness.", fullMl: 30, price: 3000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 블랙스네일 리프팅 마스크"), linkType: "search", image: "/assets/products/drg-blacksnail-lifting-mask.gif" },
  { id: "dalba-vegan-liftension-mask", brand: "달바", brandJp: "ダルバ", brandEn: "d'Alba", name: "비건 인텐시브 리프텐션 마스크", nameJp: "ヴィーガンインテンシブリフテンションマスク", nameEn: "Vegan Intensive Liftension Mask", category: "마스크팩", ingredients: ["화이트트러플", "콜라겐", "비건세라마이드", "판테놀", "센텔라"], forTypes: ["건성", "중성", "복합"], concerns: ["주름", "수분"], rating: 4.5, feel: "촉촉", desc: "농축 탄력 앰플과 텐션업 시트의 더블 케어, 탄력을 끌어올리는 비건 리프팅 마스크", descJp: "濃縮弾力アンプルとテンションアップシートのダブルケア、弾力を引き上げるヴィーガンリフティングマスク", descEn: "A vegan lifting mask combining a concentrated firming ampoule and tension-up sheet for a double-care lift.", fullMl: 35, price: 8000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 비건 인텐시브 리프텐션 마스크팩"), linkType: "search", image: "/assets/products/dalba-vegan-liftension-mask.jpg" },
  { id: "ahc-proshot-pore-eraser-mask", brand: "AHC", brandJp: "AHC", brandEn: "AHC", name: "프로샷 포어 이레이저 스피큘 세럼 인 겔 마스크", nameJp: "プロショット ポアイレーザー スピキュールセラムインジェルマスク", nameEn: "Pro-Shot Pore Eraser Spicule Serum-in-Gel Mask", category: "마스크팩", ingredients: ["스피큘", "레티놀", "글루타치온", "나이아신아마이드"], forTypes: ["복합", "지성"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "스피큘과 세럼 영양을 밀착 전달하는 모공·광채 케어 하이드로겔 마스크", descJp: "スピキュールとセラム栄養を密着デリバリーする毛穴・ツヤケアハイドロゲルマスク", descEn: "A hydrogel mask that delivers spicule and serum nutrients closely for pore and glow care.", fullMl: 28, price: 3000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("AHC 프로샷 포어이레이저 스피큘 세럼인 겔 마스크"), linkType: "search", image: "/assets/products/ahc-proshot-pore-eraser-mask.jpg" },
  { id: "manyo-galac-niacin-mask", brand: "마녀공장", brandJp: "マニョファクトリー", brandEn: "Manyo Factory", name: "갈락 나이아신 에센스 마스크", nameJp: "ガラクナイアシンエッセンスマスク", nameEn: "Galac Niacin Essence Mask", category: "마스크팩", ingredients: ["갈락토미세스발효여과물", "나이아신아마이드", "판테놀"], forTypes: ["복합", "건성", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "갈락토미세스·나이아신아마이드로 투명 광채와 톤을 케어하는 에센스 시트 마스크", descJp: "ガラクトミセス・ナイアシンアミドで透明感あるツヤとトーンをケアするエッセンスシートマスク", descEn: "An essence sheet mask with galactomyces and niacinamide for radiant glow and tone care.", fullMl: 25, price: 3000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 갈락 나이아신 에센스 마스크팩"), linkType: "search", image: "/assets/products/manyo-galac-niacin-mask.jpg" },

  // 로션·에멀전 12종 추가
  { id: "roundlab-dokdo-lotion", brand: "라운드랩", brandJp: "ラウンドラボ", brandEn: "Round Lab", name: "1025 독도 로션", nameJp: "1025独島ローション", nameEn: "1025 Dokdo Lotion", category: "로션", ingredients: ["독도해양심층수", "판테놀"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "독도해양심층수로 자극 없이 유수분 밸런스를 잡아주는 로션", descJp: "独島海洋深層水で刺激なく皮脂と水分のバランスを整えるローション", descEn: "A lotion with deep-sea water that balances oil and moisture without irritation.", fullMl: 200, price: 21000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 1025 독도 로션"), linkType: "search", image: "/assets/products/roundlab-dokdo-lotion.webp" },
  { id: "anua-heartleaf-lotion", brand: "아누아", brandJp: "アヌア", brandEn: "Anua", name: "어성초 77 히알루론산 수분 진정 로션", nameJp: "ドクダミ77 ヒアルロン酸保湿鎮静ローション", nameEn: "Heartleaf 77 Hyaluronic Acid Moisture Soothing Lotion", category: "로션", ingredients: ["어성초추출물", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "어성초 77%로 트러블과 열감을 진정시키며 수분을 채우는 로션", descJp: "ドクダミ77%でトラブルとほてりを鎮静させながら潤いを満たすローション", descEn: "A lotion with 77% heartleaf that soothes trouble and heat while hydrating.", fullMl: 200, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아누아 어성초 77 히알루론산 수분 진정 로션"), linkType: "search", image: "/assets/products/anua-heartleaf-lotion.webp" },
  { id: "manyo-bifida-biome-lotion", brand: "마녀공장", brandJp: "マニョファクトリー", brandEn: "Manyo Factory", name: "비피다 바이옴 앰플 로션", nameJp: "ビフィズスバイオームアンプルローション", nameEn: "Bifida Biome Ampoule Lotion", category: "로션", ingredients: ["비피다발효용해물", "나이아신아마이드"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분", "주름"], rating: 4.6, feel: "촉촉", desc: "비피다 발효 성분으로 장벽을 채우는 앰플 함량 로션", descJp: "ビフィズス発酵成分でバリアを満たすアンプル配合ローション", descEn: "An ampoule-strength lotion with bifida ferment to fill in the barrier.", fullMl: 300, price: 24000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 비피다 바이옴 앰플 로션"), linkType: "search", image: "/assets/products/manyo-bifida-biome-lotion.webp" },
  { id: "missha-first-essence-lotion", brand: "미샤", brandJp: "ミシャ", brandEn: "Missha", name: "타임 레볼루션 더 퍼스트 에센스 로션 5X", nameJp: "タイムレボリューション ザ・ファーストエッセンスローション5X", nameEn: "Time Revolution The First Essence Lotion 5X", category: "로션", ingredients: ["갈락토미세스발효여과물", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["주름", "기미"], rating: 4.6, feel: "촉촉", desc: "갈락토미세스 발효 에센스 함량을 높인 안티에이징 로션", descJp: "ガラクトミセス発酵エッセンスの配合量を高めたアンチエイジングローション", descEn: "An anti-aging lotion with a boosted galactomyces fermented essence content.", fullMl: 130, price: 22000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 타임 레볼루션 더 퍼스트 에센스 로션 5X"), linkType: "search", image: "/assets/products/missha-first-essence-lotion.png" },
  { id: "drjart-cicapair-lotion", brand: "닥터자르트", brandJp: "ドクタージャルト", brandEn: "Dr. Jart+", name: "시카페어 인텐시브 수딩 리페어 트리트먼트 로션", nameJp: "シカペア インテンシブスージングリペアトリートメントローション", nameEn: "Cicapair Intensive Soothing Repair Treatment Lotion", category: "로션", ingredients: ["병풀추출물", "마데카소사이드"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "시카 콤플렉스로 예민해진 피부 장벽을 리페어하는 진정 로션", descJp: "シカコンプレックスで敏感になった肌バリアをリペアする鎮静ローション", descEn: "A soothing lotion with cica complex that repairs a sensitized skin barrier.", fullMl: 150, price: 42000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터자르트 시카페어 인텐시브 수딩 리페어 트리트먼트 로션"), linkType: "search", image: "/assets/products/drjart-cicapair-lotion.webp" },
  { id: "drjart-ceramidin-lotion", brand: "닥터자르트", brandJp: "ドクタージャルト", brandEn: "Dr. Jart+", name: "세라마이딘 스킨 베리어 모이스처라이징 밀키 로션", nameJp: "セラミジン スキンバリアモイスチャライジングミルキーローション", nameEn: "Ceramidin Skin Barrier Moisturizing Milky Lotion", category: "로션", ingredients: ["세라마이드", "히알루론산"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.7, feel: "보습", desc: "세라마이딘 성분으로 피부 장벽을 채우는 고보습 밀키 로션", descJp: "セラミジン成分で肌バリアを満たす高保湿ミルキーローション", descEn: "A highly moisturizing, milky lotion with ceramidin to fill in the skin barrier.", fullMl: 50, price: 47000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터자르트 세라마이딘 스킨 베리어 모이스처라이징 밀키 로션"), linkType: "search", image: "/assets/products/drjart-ceramidin-lotion.webp" },
  { id: "biohealboh-probioderm-emulsion", brand: "바이오힐보", brandJp: "バイオヒールボ", brandEn: "Bioheal BO", name: "프로바이오덤 리페어 에멀전", nameJp: "プロバイオダーム リペア乳液", nameEn: "Probioderm Repair Emulsion", category: "로션", ingredients: ["병풀추출물", "프로바이오틱스"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "프로바이오틱스로 피부 장벽과 유수분 밸런스를 리페어하는 에멀전", descJp: "プロバイオティクスで肌バリアと皮脂・水分バランスをリペアする乳液", descEn: "An emulsion with probiotics that repairs the skin barrier and oil-water balance.", fullMl: 150, price: 24000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("바이오힐보 프로바이오덤 리페어 에멀전"), linkType: "search", image: "/assets/products/biohealboh-probioderm-emulsion.jpeg" },
  { id: "naturerepublic-snail-emulsion", brand: "네이처리퍼블릭", brandJp: "ネイチャーリパブリック", brandEn: "Nature Republic", name: "스네일 솔루션 에멀전", nameJp: "スネイルソリューション乳液", nameEn: "Snail Solution Emulsion", category: "로션", ingredients: ["달팽이점액여과물"], forTypes: ["건성", "복합", "중성"], concerns: ["수분", "주름"], rating: 4.4, feel: "촉촉", desc: "달팽이점액여과물로 탄력과 수분을 채우는 데일리 에멀전", descJp: "カタツムリ分泌濾過物で弾力と潤いを満たすデイリー乳液", descEn: "A daily emulsion with snail secretion filtrate for firmness and hydration.", fullMl: 120, price: 19000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("네이처리퍼블릭 스네일 솔루션 에멀전"), linkType: "search", image: "/assets/products/naturerepublic-snail-emulsion.jpeg" },
  { id: "bringgreen-bluebean-pdrn-lotion", brand: "브링그린", brandJp: "ブリングリーン", brandEn: "Bring Green", name: "블루빈 B5 PDRN 마일드 로션", nameJp: "ブルービーン B5 PDRNマイルドローション", nameEn: "Blue Bean B5 PDRN Mild Lotion", category: "로션", ingredients: ["PDRN", "판테놀"], forTypes: ["건성", "민감", "복합"], concerns: ["수분", "주름"], rating: 4.5, feel: "촉촉", desc: "PDRN·판테놀로 순하게 수분과 탄력을 채우는 마일드 로션", descJp: "PDRN・パンテノールでやさしく潤いと弾力を満たすマイルドローション", descEn: "A mild lotion with PDRN and panthenol that gently fills in hydration and firmness.", fullMl: 230, price: 18000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("브링그린 블루빈 B5 PDRN 마일드 로션"), linkType: "search", image: "/assets/products/bringgreen-bluebean-pdrn-lotion.jpeg" },
  { id: "dalba-white-truffle-lotion", brand: "달바", brandJp: "ダルバ", brandEn: "d'Alba", name: "화이트 트러플 모이스처라이징 세럼 로션", nameJp: "ホワイトトリュフモイスチャライジングセラムローション", nameEn: "White Truffle Moisturizing Serum Lotion", category: "로션", ingredients: ["화이트트러플추출물", "나이아신아마이드"], forTypes: ["건성", "중성", "복합"], concerns: ["수분", "기미"], rating: 4.6, feel: "촉촉", desc: "화이트 트러플 추출물로 윤기와 수분을 채우는 세럼 로션", descJp: "ホワイトトリュフ抽出物でツヤと潤いを満たすセラムローション", descEn: "A serum-lotion with white truffle extract for radiance and hydration.", fullMl: 100, price: 42000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 화이트 트러플 모이스처라이징 세럼 로션"), linkType: "search", image: "/assets/products/dalba-white-truffle-lotion.jpeg" },
  { id: "missha-superaqua-emulsion", brand: "미샤", brandJp: "ミシャ", brandEn: "Missha", name: "수퍼 아쿠아 울트라 히알론 에멀전", nameJp: "スーパーアクア ウルトラヒアルロン乳液", nameEn: "Super Aqua Ultra Hyalron Emulsion", category: "로션", ingredients: ["히알루론산"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "히알루론산으로 촉촉함을 채우는 데일리 수분 에멀전", descJp: "ヒアルロン酸でしっとり感を満たすデイリー保湿乳液", descEn: "A daily hydrating emulsion with hyaluronic acid for a dewy feel.", fullMl: 130, price: 19000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 수퍼 아쿠아 울트라 히알론 에멀전"), linkType: "search", image: "/assets/products/missha-superaqua-emulsion.jpeg" },
  { id: "drg-red-blemish-multi-fluid", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "레드 블레미쉬 멀티 플루이드", nameJp: "レッドブレミッシュ マルチフルイド", nameEn: "Red Blemish Multi Fluid", category: "로션", ingredients: ["센텔라", "시카"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "레드 블레미쉬 라인의 산뜻한 플루이드 타입 진정 로션", descJp: "レッドブレミッシュラインのさっぱりしたフルイドタイプ鎮静ローション", descEn: "A refreshing fluid-type soothing lotion from the Red Blemish line.", fullMl: 100, price: 29000, safety: ["진정", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 멀티 플루이드"), linkType: "search", image: "/assets/products/drg-red-blemish-multi-fluid.png" },
  { id: "estra-atobarrier", brand: "에스트라", brandJp: "エストラ", brandEn: "Estra", name: "아토베리어365 크림", nameJp: "アトバリア365 クリーム", nameEn: "Atobarrier 365 Cream", category: "크림", ingredients: ["세라마이드"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.68, feel: "보습", desc: "세라마이드로 피부장벽을 강화하는 고보습 진정 크림", descJp: "セラミドで肌バリアを強化する高保湿鎮静クリーム", descEn: "Ceramide-rich, deeply moisturizing cream that soothes and strengthens the skin barrier.", fullMl: 80, price: 32000, safety: ["무향", "저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000198320", linkType: "direct", image: "/assets/products/estra-atobarrier.png" },
  { id: "drg-red-blemish", brand: "닥터지", brandJp: "ドクタージー", brandEn: "Dr.G", name: "레드 블레미쉬 클리어 수딩 크림", nameJp: "レッドブレミッシュ クリアスージングクリーム", nameEn: "Red Blemish Clear Soothing Cream", category: "크림", ingredients: ["센텔라", "시카"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블"], rating: 4.5, feel: "진정", desc: "붉은기·민감을 진정시키는 수딩크림", descJp: "赤み・敏感肌を鎮静させるスージングクリーム", descEn: "A soothing cream that calms redness and sensitivity.", fullMl: 70, price: 30000, safety: ["진정", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000164615", linkType: "direct", image: "/assets/products/drg-red-blemish.jpg" },
  { id: "esnature-squalane", brand: "에스네이처", brandJp: "エスネイチャー", brandEn: "Esnature", name: "아쿠아 스쿠알란 수분크림", nameJp: "アクアスクワラン モイスチャークリーム", nameEn: "Aqua Squalane Moisture Cream", category: "크림", ingredients: ["스쿠알란"], forTypes: ["건성", "중성"], concerns: ["수분"], rating: 4.58, feel: "보습", desc: "스쿠알란으로 유수분 밸런스를 맞추는 수분크림", descJp: "スクワランで皮脂と水分のバランスを整える保湿クリーム", descEn: "A moisture cream with squalane to balance oil and water.", fullMl: 60, price: 27000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("에스네이처 아쿠아 스쿠알란 수분크림"), linkType: "search", image: "/assets/products/esnature-squalane.jpg" },
  { id: "wellage-soothing", brand: "웰라쥬", brandJp: "ウェラージュ", brandEn: "Wellage", name: "리얼 히알루로닉 수딩크림", nameJp: "リアルヒアルロニック スージングクリーム", nameEn: "Real Hyaluronic Soothing Cream", category: "크림", ingredients: ["히알루론산"], forTypes: ["민감", "건성"], concerns: ["수분", "트러블"], rating: 4.6, feel: "진정", desc: "진정+보습을 동시에 주는 수딩크림", descJp: "鎮静と保湿を同時に叶えるスージングクリーム", descEn: "A cream that soothes and hydrates at the same time.", fullMl: 80, price: 28000, safety: ["진정"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("웰라쥬 리얼 히알루로닉 수딩크림"), linkType: "search", image: "/assets/products/wellage-soothing.jpg" },
];

export type WxProfile = { temp: number; humidity: number; uv: number; dust: number };
export type Recommendation = { p: Cosmetic; reason: string; reasonJp: string; reasonEn: string };

// 언어 전환(KO/JP/EN) — 추천 요약·이유 문장에 쓰이는 고정 어휘(유한 집합) 번역 사전
const SKINTYPE_TR: Record<string, { jp: string; en: string }> = {
  "건성": { jp: "乾燥肌", en: "dry skin" },
  "지성": { jp: "脂性肌", en: "oily skin" },
  "민감성": { jp: "敏感肌", en: "sensitive skin" },
};
const CONCERN_TR: Record<string, { jp: string; en: string }> = {
  "수분": { jp: "水分", en: "Hydration" },
  "트러블": { jp: "トラブル", en: "Blemishes" },
  "기미": { jp: "シミ", en: "Spots" },
  "주름": { jp: "シワ", en: "Wrinkles" },
};

export function normType(t: string) {
  return t.replace("복합성", "복합").replace("민감성", "민감");
}

export function recommendCosmetics(
  skinTypeForRec: string,
  sensitivity: string,
  concerns: string[],
  wx: WxProfile,
  userAllergies: string[] = []
): { summary: string; summaryJp: string; summaryEn: string; items: Recommendation[] } {
  const skin = normType(skinTypeForRec);
  const dry = wx.humidity <= 45;
  const hotHumid = wx.temp >= 30 && wx.humidity >= 70;
  const hiUV = wx.uv >= 8;
  const hiDust = wx.dust >= 80;

  // 등록된 알러지 성분과 겹치는 제품은 어떤 추천 목록에도 나오지 않도록 아예 제외한다.
  const scored = COSMETICS.filter((p) => allergyRiskForProduct(userAllergies, p.ingredients, p.safety, fullIngredientsFor(p.id)).length === 0).map((p) => {
    let s = 0;
    if (p.forTypes.includes(skin)) s += 3;
    const matched = concerns.filter((c) => p.concerns.includes(c));
    s += matched.length * 2;
    s += (p.rating - 4.3) * 4;
    if (sensitivity === "민감") {
      if (p.forTypes.includes("민감")) s += 1.5;
      if (p.feel === "진정") s += 1;
    }
    if (dry && p.concerns.includes("수분")) s += 2;
    if (hotHumid) {
      if (p.feel === "산뜻") s += 1.5;
      if (["클렌징", "토너", "선크림"].includes(p.category)) s += 0.6;
    }
    if (hiUV) {
      if (p.category === "선크림") s += 2.5;
      if (p.concerns.includes("기미")) s += 1;
    }
    if (hiDust && (p.concerns.includes("트러블") || p.category === "클렌징")) s += 1;
    return { p, s, matched };
  });

  scored.sort((a, b) => b.s - a.s || b.p.rating - a.p.rating);

  // 카테고리별로 가장 점수가 높은 제품 1개만 후보로 남긴다 — "카테고리별 대표" 추천이라는
  // 취지대로, 같은 카테고리(예: 토너 2개)가 중복으로 추천되지 않게 하고 클렌징폼처럼
  // 전체 경쟁에서 밀리기 쉬운 카테고리도 항상 하나는 포함되게 한다.
  const seenCategory = new Set<string>();
  const top = scored.filter(({ p }) => {
    if (seenCategory.has(p.category)) return false;
    seenCategory.add(p.category);
    return true;
  });

  const skinTr = SKINTYPE_TR[skinTypeForRec] ?? { jp: skinTypeForRec, en: skinTypeForRec };

  const items: Recommendation[] = top.map(({ p, matched }) => {
    const bits: string[] = [];
    const bitsJp: string[] = [];
    const bitsEn: string[] = [];
    if (p.forTypes.includes(skin)) {
      bits.push(`${skinTypeForRec} 피부 적합`);
      bitsJp.push(`${skinTr.jp}に適合`);
      bitsEn.push(`Great fit for ${skinTr.en}`);
    }
    if (p.ingredients[0]) {
      bits.push(`${p.ingredients[0]} 함유`);
      bitsJp.push(`${p.ingredients[0]}配合`);
      bitsEn.push(`Contains ${p.ingredients[0]}`);
    }
    if (hiUV && p.category === "선크림") {
      bits.push("강한 자외선 차단");
      bitsJp.push("強い紫外線カット");
      bitsEn.push("Strong UV protection");
    } else if (hiDust && p.category === "클렌징") {
      bits.push("미세먼지 많은 날 클렌징 케어");
      bitsJp.push("微細粉塵の多い日のクレンジングケア");
      bitsEn.push("Cleansing care for high-dust days");
    } else if (dry && p.concerns.includes("수분")) {
      bits.push("건조한 기후 속보습");
      bitsJp.push("乾燥した気候でのインナー保湿");
      bitsEn.push("Deep hydration for dry climates");
    } else if (hotHumid && p.feel === "산뜻") {
      bits.push("습한 날 산뜻하게");
      bitsJp.push("湿度が高い日もさっぱり");
      bitsEn.push("Refreshing on humid days");
    } else if (matched[0]) {
      const c = CONCERN_TR[matched[0]];
      bits.push(`'${matched[0]}' 고민 케어`);
      bitsJp.push(`「${c?.jp ?? matched[0]}」ケア`);
      bitsEn.push(`${c?.en ?? matched[0]} care`);
    }
    return {
      p,
      reason: bits.slice(0, 3).join(" · "),
      reasonJp: bitsJp.slice(0, 3).join(" · "),
      reasonEn: bitsEn.slice(0, 3).join(" · "),
    };
  });

  const driver = hiUV ? "강한 자외선" : dry ? "건조한 공기" : hotHumid ? "고온다습" : hiDust ? "높은 미세먼지" : "쾌적한 날씨";
  const driverJp = hiUV ? "強い紫外線" : dry ? "乾燥した空気" : hotHumid ? "高温多湿" : hiDust ? "高い微細粉塵" : "快適な天気";
  const driverEn = hiUV ? "strong UV" : dry ? "dry air" : hotHumid ? "hot and humid weather" : hiDust ? "high fine dust" : "pleasant weather";
  const approach =
    sensitivity === "민감"
      ? "진정 성분(센텔라·판테놀)"
      : skin === "건성"
        ? "고보습(히알루론산·세라마이드)"
        : skin === "지성"
          ? "피지 케어(BHA·나이아신)"
          : "수분·톤 밸런스";
  const approachJp =
    sensitivity === "민감"
      ? "鎮静成分（ツボクサ・パンテノール）"
      : skin === "건성"
        ? "高保湿（ヒアルロン酸・セラミド）"
        : skin === "지성"
          ? "皮脂ケア（BHA・ナイアシン）"
          : "水分・トーンバランス";
  const approachEn =
    sensitivity === "민감"
      ? "soothing ingredients (Centella, Panthenol)"
      : skin === "건성"
        ? "deep hydration (Hyaluronic acid, Ceramide)"
        : skin === "지성"
          ? "sebum care (BHA, Niacinamide)"
          : "hydration & tone balance";
  const sun = hiUV ? " + 무기자차 선크림" : "";
  const sunJp = hiUV ? " + ノンケミカル日焼け止め" : "";
  const sunEn = hiUV ? " + mineral sunscreen" : "";
  const summary = `${skinTypeForRec} + ${driver} → ${approach}${sun} → 아래 추천`;
  const summaryJp = `${skinTr.jp} + ${driverJp} → ${approachJp}${sunJp} → 下記のおすすめ`;
  const summaryEn = `${skinTr.en} + ${driverEn} → ${approachEn}${sunEn} → recommendations below`;

  return { summary, summaryJp, summaryEn, items };
}

/* ── [5-4] 소용량 샘플 로직 ── */
export const SAMPLE_TIERS = [10, 20, 30, 50, 75];
const DAILY_USAGE: Record<string, number> = { 토너: 2.0, 세럼: 1.0, 앰플: 1.0, 크림: 1.5, 선크림: 2.0, 클렌징: 2.0 };
const MOIST_CATS = ["토너", "크림", "앰플", "세럼"];

// 본품 용량(fullMl)보다 작은 샘플 티어만 유효 — 본품보다 크거나 같은 "샘플"은 의미가 없다.
export function validSampleTiers(fullMl: number) {
  return SAMPLE_TIERS.filter((t) => t < fullMl);
}

export function dailyUsage(category: string) {
  return DAILY_USAGE[category] ?? 1.5;
}

// 여행 일수 + 기후로 추천 용량 티어 산출. 샘플 티어는 본품 용량(fullMl)보다 작은
// 것만 유효하며, 필요 용량이 본품 용량 이상이면 샘플 대신 본품 구매를 추천한다(full: true).
export function recommendVolume(category: string, days: number, dryHigh: boolean, uvHigh: boolean, fullMl: number) {
  const need = dailyUsage(category) * days * 1.2;
  const validTiers = validSampleTiers(fullMl);
  if (validTiers.length === 0) {
    return { ml: 0, qty: 0, need: Math.round(need), full: true };
  }
  let idx = validTiers.findIndex((t) => t >= need);
  if (idx === -1) idx = validTiers.length - 1;
  if (dryHigh && MOIST_CATS.includes(category)) idx = Math.min(validTiers.length - 1, idx + 1);
  if (uvHigh && category === "선크림") idx = Math.min(validTiers.length - 1, idx + 1);
  const ml = validTiers[idx];
  const full = need >= fullMl;
  const qty = ml >= 75 && need > 75 && !full ? Math.ceil(need / 75) : 1;
  return { ml, qty, need: Math.round(need), full };
}

// ml당 단가 기준 소용량 금액 (100원 반올림)
export function samplePrice(price: number, fullMl: number, ml: number) {
  const per = price / fullMl;
  return Math.round((per * ml) / 100) * 100;
}
