// 화해 리뷰 랭킹 기반 실제 제품 데이터 (별점은 참고용 근사값).
// fullMl/price 는 카테고리 기준 근사값(수정 가능), oliveYoungUrl 은 제품명 검색 링크.
// image: 실제 제품 이미지 URL을 넣으면 노출, 비어 있으면 브랜드 컬러 플레이스홀더로 폴백.

import { allergyRiskForProduct } from "./allergens-data";

export type Cosmetic = {
  id: string;
  brand: string;
  name: string;
  category: string; // 세럼/크림/토너/앰플/클렌징/선크림/마스크팩/로션
  ingredients: string[];
  forTypes: string[]; // 건성/지성/복합/중성/민감
  concerns: string[]; // 주름/기미/수분/트러블
  rating: number;
  feel: string; // 산뜻/보습/진정/촉촉
  desc: string;
  fullMl: number; // 정품 용량
  price: number; // 정가(원, 근사·참고용)
  safety: string[]; // 약산성/무향/저자극/무기자차 등
  oliveYoungUrl: string;
  linkType: "direct" | "search"; // direct=개별 상품페이지, search=검색 폴백
  image?: string;
};

// 올리브영 실제 판매 제품 기반 큐레이션 (실시간 연동 아님). 정가는 근사·참고용.
export const COSMETICS: Cosmetic[] = [
  { id: "toriden-divein", brand: "토리든", name: "다이브인 저분자 히알루론산 세럼", category: "세럼", ingredients: ["히알루론산"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.6, feel: "산뜻", desc: "저분자 히알루론산으로 속보습을 빠르게 채워주는 스테디셀러", fullMl: 50, price: 22000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000128643", linkType: "direct" },
  { id: "estra-atobarrier", brand: "에스트라", name: "아토베리어365 크림", category: "크림", ingredients: ["세라마이드"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.68, feel: "보습", desc: "세라마이드로 피부장벽을 강화하는 고보습 진정 크림", fullMl: 80, price: 32000, safety: ["무향", "저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000198320", linkType: "direct" },
  { id: "anua-pdrn", brand: "아누아", name: "PDRN 히알루론산 캡슐 100 세럼", category: "세럼", ingredients: ["PDRN", "히알루론산"], forTypes: ["건성", "복합", "중성"], concerns: ["수분", "주름"], rating: 4.6, feel: "촉촉", desc: "PDRN+히알루론산으로 탄력·보습을 함께 잡는 세럼", fullMl: 30, price: 26000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000231894", linkType: "direct" },
  { id: "esnature-aqua-toner", brand: "에스네이처", name: "아쿠아 오아시스 토너", category: "토너", ingredients: ["히알루론산"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.74, feel: "산뜻", desc: "가볍게 수분을 채워주는 데일리 수분 토너", fullMl: 300, price: 21000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000158369", linkType: "direct" },
  { id: "wellage-blue-ampoule", brand: "웰라쥬", name: "리얼 히알루로닉 블루 100 앰플", category: "앰플", ingredients: ["히알루론산"], forTypes: ["건성", "복합", "민감"], concerns: ["수분"], rating: 4.66, feel: "촉촉", desc: "히알루론산 앰플로 집중 수분 공급", fullMl: 100, price: 30000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000147809", linkType: "direct" },
  { id: "roundlab-birch-sun", brand: "라운드랩", name: "자작나무 수분 선크림 SPF50+", category: "선크림", ingredients: ["자작나무수액"], forTypes: ["건성", "중성", "복합", "민감"], concerns: ["수분"], rating: 4.6, feel: "촉촉", desc: "촉촉하게 발리는 데일리 수분 선크림", fullMl: 50, price: 25000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000149135", linkType: "direct" },
  { id: "roundlab-dokdo-toner", brand: "라운드랩", name: "1025 독도 토너", category: "토너", ingredients: ["미네랄", "진정"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "산뜻", desc: "자극 없이 결을 정돈하는 진정 토너", fullMl: 200, price: 15000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000132162", linkType: "direct", image: "/assets/products/roundlab-dokdo-toner.webp" },
  { id: "beplain-mungbean", brand: "비플레인", name: "녹두 약산성 클렌징폼", category: "클렌징", ingredients: ["약산성", "녹두"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.63, feel: "산뜻", desc: "피지·모공 관리에 좋은 약산성 클렌징", fullMl: 80, price: 12000, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000142520", linkType: "direct" },
  { id: "toriden-divein-cleansing", brand: "토리든", name: "다이브인 저분자 히알루론산 클렌징 폼", category: "클렌징", ingredients: ["히알루론산", "저분자"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.7, feel: "촉촉", desc: "세안 후에도 당기지 않게 속보습을 남기는 저자극 폼", fullMl: 150, price: 16000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("토리든 다이브인 저분자 히알루론산 클렌징 폼"), linkType: "search" },
  { id: "esnature-aqua-rice-cleansing", brand: "에스네이처", name: "아쿠아 라이스 약산성 클렌징 폼", category: "클렌징", ingredients: ["쌀추출물", "약산성"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.7, feel: "산뜻", desc: "쌀 성분으로 순하게 씻어내는 약산성 데일리 폼", fullMl: 160, price: 19000, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("에스네이처 아쿠아 라이스 약산성 클렌징 폼"), linkType: "search" },
  { id: "shenli-kelp-cleansing", brand: "션리", name: "다시마 앰플 클렌징폼", category: "클렌징", ingredients: ["다시마", "미네랄"], forTypes: ["지성", "복합", "중성"], concerns: ["수분", "트러블"], rating: 4.5, feel: "촉촉", desc: "다시마 앰플 성분으로 세안 후에도 속당김 없이 촉촉하게", fullMl: 120, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("션리 다시마 앰플 클렌징폼"), linkType: "search" },
  { id: "suiskin-sprout-cleansing", brand: "수이스킨", name: "어린새싹 딥 클렌징 폼", category: "클렌징", ingredients: ["새싹추출물"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.6, feel: "산뜻", desc: "모공 속 노폐물까지 개운하게 씻어내는 딥 클렌징 폼", fullMl: 150, price: 14000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("수이스킨 어린새싹 딥 클렌징 폼"), linkType: "search" },
  { id: "illiyoon-ceramide-wash", brand: "일리윤", name: "세라마이드 아토 6.0 탑투토 워시", category: "클렌징", ingredients: ["세라마이드"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.7, feel: "보습", desc: "얼굴부터 몸까지, 순하게 세안하며 장벽을 지키는 약산성 워시", fullMl: 500, price: 14000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("일리윤 세라마이드 아토 6.0 탑투토 워시"), linkType: "search" },
  { id: "goodal-vitac", brand: "구달", name: "청귤 비타C 잡티케어 세럼", category: "세럼", ingredients: ["비타민C"], forTypes: ["중성", "복합", "지성"], concerns: ["기미"], rating: 4.5, feel: "산뜻", desc: "비타민C로 잡티·톤 케어하는 브라이트닝 세럼", fullMl: 30, price: 27000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162325", linkType: "direct" },
  { id: "drg-red-blemish", brand: "닥터지", name: "레드 블레미쉬 클리어 수딩 크림", category: "크림", ingredients: ["센텔라", "시카"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블"], rating: 4.5, feel: "진정", desc: "붉은기·민감을 진정시키는 수딩크림", fullMl: 70, price: 30000, safety: ["진정", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000164615", linkType: "direct" },
  { id: "layerlab-panthenol", brand: "레이어랩", name: "니오좀 판테놀 5% 세럼", category: "세럼", ingredients: ["판테놀"], forTypes: ["민감", "건성"], concerns: ["수분", "트러블"], rating: 4.6, feel: "진정", desc: "판테놀 고함량으로 예민해진 피부를 진정시키는 세럼", fullMl: 30, price: 34000, safety: ["진정"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("레이어랩 니오좀 판테놀 5% 세럼"), linkType: "search" },
  { id: "esnature-squalane", brand: "에스네이처", name: "아쿠아 스쿠알란 수분크림", category: "크림", ingredients: ["스쿠알란"], forTypes: ["건성", "중성"], concerns: ["수분"], rating: 4.58, feel: "보습", desc: "스쿠알란으로 유수분 밸런스를 맞추는 수분크림", fullMl: 60, price: 27000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("에스네이처 아쿠아 스쿠알란 수분크림"), linkType: "search" },
  { id: "wellage-soothing", brand: "웰라쥬", name: "리얼 히알루로닉 수딩크림", category: "크림", ingredients: ["히알루론산"], forTypes: ["민감", "건성"], concerns: ["수분", "트러블"], rating: 4.6, feel: "진정", desc: "진정+보습을 동시에 주는 수딩크림", fullMl: 80, price: 28000, safety: ["진정"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("웰라쥬 리얼 히알루로닉 수딩크림"), linkType: "search" },
  { id: "tonymoly-ceramide", brand: "토니모리", name: "세라마이드 모찌 토너", category: "토너", ingredients: ["세라마이드"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.69, feel: "보습", desc: "세라마이드로 장벽을 채워주는 촉촉 토너", fullMl: 300, price: 13000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("토니모리 세라마이드 모찌 토너"), linkType: "search" },
  { id: "innisfree-retinol-cica", brand: "이니스프리", name: "레티놀 시카 흔적 앰플", category: "앰플", ingredients: ["레티놀", "시카"], forTypes: ["복합", "지성", "중성"], concerns: ["주름", "트러블"], rating: 4.5, feel: "진정", desc: "레티놀+시카로 탄력·흔적 케어", fullMl: 30, price: 33000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("이니스프리 레티놀 시카 흔적 앰플"), linkType: "search" },
  { id: "drg-green-sun", brand: "닥터지", name: "그린 마일드 업 선 플러스 SPF50+", category: "선크림", ingredients: ["무기자차", "시카"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블"], rating: 4.5, feel: "산뜻", desc: "민감·지성도 편한 순한 무기자차 선크림", fullMl: 50, price: 26000, safety: ["무기자차", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 그린 마일드 업 선"), linkType: "search" },
  { id: "clio-noscarnine", brand: "클리오", name: "노스카나인 트러블 세럼", category: "세럼", ingredients: ["노스카나인", "BHA"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.4, feel: "산뜻", desc: "트러블·피지 집중 케어 세럼", fullMl: 20, price: 20000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("클리오 노스카나인 트러블 세럼"), linkType: "search" },
  { id: "numbuzin-no1", brand: "넘버즈인", name: "1번 시그니처 세럼", category: "세럼", ingredients: ["나이아신아마이드"], forTypes: ["지성", "복합", "중성"], concerns: ["기미", "트러블"], rating: 4.4, feel: "산뜻", desc: "나이아신아마이드로 피지·톤을 정돈", fullMl: 50, price: 28000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("넘버즈인 1번 시그니처 세럼"), linkType: "search" },
  { id: "ahc-herb-rose-toner", brand: "AHC", name: "허브솔루션 로즈 토너", category: "토너", ingredients: ["다마스크장미꽃수"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "다마스크 장미꽃수로 산뜻하게 결을 정돈하는 대용량 토너", fullMl: 500, price: 13800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165364", linkType: "direct", image: "/assets/products/ahc-herb-rose-toner.webp" },
  { id: "numbuzin-no3-toner", brand: "넘버즈인", name: "3번 보들보들 퍼스트 결부스팅 토너", category: "토너", ingredients: ["나이아신아마이드", "세라마이드", "판테놀"], forTypes: ["지성", "복합", "중성"], concerns: ["수분", "트러블"], rating: 4.5, feel: "산뜻", desc: "나이아신아마이드로 피부결을 정돈하는 자극 없는 데일리 토너", fullMl: 200, price: 24000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000250711", linkType: "direct", image: "/assets/products/numbuzin-no3-toner.webp" },
  { id: "abib-heartleaf-toner", brand: "아비브", name: "어성초 카밍 토너 스킨 부스터", category: "토너", ingredients: ["어성초추출물", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "지리산 어성초 추출물로 열감을 식혀주는 쿨링 진정 토너", fullMl: 200, price: 23000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000155253", linkType: "direct", image: "/assets/products/abib-heartleaf-toner.jpg" },
  { id: "drg-aclear-toner", brand: "닥터지", name: "에이클리어 밸런싱 토너", category: "토너", ingredients: ["살리실산", "마데카소사이드"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.52, feel: "산뜻", desc: "과잉 피지와 각질을 정돈하는 약산성 저자극 토너", fullMl: 200, price: 25000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165710", linkType: "direct", image: "/assets/products/drg-aclear-toner.webp" },
  { id: "ahc-herb-witchhazel-toner", brand: "AHC", name: "허브솔루션 위치하젤 토너", category: "토너", ingredients: ["위치하젤"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.2, feel: "산뜻", desc: "위치하젤로 모공과 피지를 산뜻하게 정돈하는 토너", fullMl: 500, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165355", linkType: "direct", image: "/assets/products/ahc-herb-witchhazel-toner.webp" },
  { id: "blancdoux-oligo-toner", brand: "더랩바이블랑두", name: "올리고 히알루론산 저분자 딥 토너", category: "토너", ingredients: ["올리고히알루론산", "히알루론산"], forTypes: ["건성", "민감"], concerns: ["수분"], rating: 4.7, feel: "촉촉", desc: "저분자 히알루론산이 각질층까지 빠르게 채우는 딥 토너", fullMl: 200, price: 15100, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("더랩바이블랑두 올리고 히알루론산 저분자 딥 토너"), linkType: "search", image: "/assets/products/blancdoux-oligo-toner.webp" },
  { id: "bringgreen-teatree-toner", brand: "브링그린", name: "티트리 시카 수딩 토너", category: "토너", ingredients: ["티트리추출물", "병풀"], forTypes: ["지성", "민감", "복합"], concerns: ["트러블"], rating: 4.53, feel: "진정", desc: "티트리와 시카로 트러블 피부를 순하게 진정시키는 토너", fullMl: 500, price: 27000, safety: ["무알코올", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189181", linkType: "direct", image: "/assets/products/bringgreen-teatree-toner.webp" },
  { id: "manyo-pantheto-toner", brand: "마녀공장", name: "판테토인 에센스 토너", category: "토너", ingredients: ["판테토인", "병풀"], forTypes: ["건성", "복합", "민감"], concerns: ["수분"], rating: 4.68, feel: "촉촉", desc: "판테토인 성분으로 빠르고 깊은 속보습을 채우는 에센스 토너", fullMl: 200, price: 32000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000199405", linkType: "direct", image: "/assets/products/manyo-pantheto-toner.webp" },
  { id: "easydew-melatoning-toner", brand: "이지듀", name: "멜라토닝 울트라카밍 토너 시카알로에", category: "토너", ingredients: ["시카", "알로에"], forTypes: ["민감", "복합"], concerns: ["트러블", "기미"], rating: 4.4, feel: "진정", desc: "시카·알로에가 피부 열감과 자극을 빠르게 진정시키는 토너", fullMl: 130, price: 31800, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("이지듀 멜라토닝 울트라카밍 토너 시카알로에"), linkType: "search", image: "/assets/products/easydew-melatoning-toner.png" },
  { id: "roundlab-birch-toner", brand: "라운드랩", name: "자작나무 수분 토너", category: "토너", ingredients: ["자작나무수액", "히알루론산"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.39, feel: "촉촉", desc: "자작나무 수액이 촉촉하게 채워주는 수분 앰플 토너", fullMl: 300, price: 23800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000148252", linkType: "direct", image: "/assets/products/roundlab-birch-toner.webp" },
  { id: "fation-noscarnine-toner", brand: "파티온", name: "노스카나인 트러블 클리어 토너", category: "토너", ingredients: ["노스카나인", "알란토인"], forTypes: ["지성", "민감"], concerns: ["트러블"], rating: 4.4, feel: "산뜻", desc: "살리실산 유도체로 트러블 피부를 진정시키는 약산성 토너", fullMl: 200, price: 19900, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000182787", linkType: "direct", image: "/assets/products/fation-noscarnine-toner.webp" },
  { id: "ahc-herb-lemon-toner", brand: "AHC", name: "허브솔루션 레몬 토너", category: "토너", ingredients: ["레몬추출물"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.2, feel: "산뜻", desc: "상큼한 레몬 향으로 피지와 유분을 산뜻하게 정돈하는 토너", fullMl: 500, price: 15000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165366", linkType: "direct", image: "/assets/products/ahc-herb-lemon-toner.webp" },
  { id: "scinic-hyaluronic-skin", brand: "싸이닉", name: "히아루론산 앰플 스킨", category: "토너", ingredients: ["히알루론산", "마데카소사이드"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.4, feel: "촉촉", desc: "5중 히알루론산이 촘촘하게 채우는 순한 수분 앰플 스킨", fullMl: 150, price: 18000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("싸이닉 히아루론산 앰플 스킨"), linkType: "search", image: "/assets/products/scinic-hyaluronic-skin.jpg" },
  { id: "numbuzin-no5-glutathione", brand: "넘버즈인", name: "5번 글루타치온C 흔적 앰플", category: "앰플", ingredients: ["글루타치온", "비타민C", "트라넥삼산", "나이아신아마이드"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["기미"], rating: 4.6, feel: "산뜻", desc: "글루타치온·비타민C·트라넥삼산으로 흔적·잡티를 밝혀주는 브라이트닝 앰플", fullMl: 30, price: 28000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("넘버즈인 5번 글루타치온C 흔적 앰플"), linkType: "search", image: "/assets/products/numbuzin-no5-glutathione.jpeg" },
  { id: "missha-vitac-plus-ampoule", brand: "미샤", name: "비타씨플러스 잡티씨 탄력 앰플", category: "앰플", ingredients: ["비타민C", "나이아신아마이드", "아데노신", "프로폴리스"], forTypes: ["건성", "지성", "복합", "중성"], concerns: ["기미", "주름"], rating: 4.6, feel: "산뜻", desc: "비타민C·나이아신아마이드로 잡티를 밝히고 탄력까지 잡는 이중기능성 앰플", fullMl: 40, price: 28000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 비타씨플러스 잡티씨 탄력 앰플"), linkType: "search", image: "/assets/products/missha-vitac-plus-ampoule.jpeg" },
  { id: "missha-time-revolution-night-repair", brand: "미샤", name: "타임 레볼루션 나이트 리페어 보랏빛 앰플 5X", category: "앰플", ingredients: ["비피다발효용해물", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["주름", "수분", "기미"], rating: 4.7, feel: "촉촉", desc: "비피다 발효 성분으로 밤사이 피부를 재생·보습하는 나이트 리페어 앰플", fullMl: 70, price: 36000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 타임 레볼루션 나이트 리페어 보랏빛 앰플 5X"), linkType: "search", image: "/assets/products/missha-time-revolution-night-repair.jpeg" },
  { id: "missha-bee-pollen-ampouler", brand: "미샤", name: "비폴렌 리뉴 앰풀러", category: "앰플", ingredients: ["화분추출물", "프로폴리스", "꿀추출물", "판테놀"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "트러블", "주름"], rating: 4.6, feel: "진정", desc: "비폴렌·프로폴리스로 피부를 진정하고 밀도를 채우는 항산화 앰플", fullMl: 40, price: 28000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 비폴렌 리뉴 앰풀러"), linkType: "search", image: "/assets/products/missha-bee-pollen-ampouler.png" },
  { id: "goodal-vitac15-ampoule", brand: "구달", name: "청귤 비타C 15 잡티 케어 앰플", category: "앰플", ingredients: ["비타민C", "청귤추출물", "나이아신아마이드", "글루타치온"], forTypes: ["건성", "지성", "복합", "중성"], concerns: ["기미"], rating: 4.4, feel: "산뜻", desc: "순수 비타민C 15%·청귤추출물로 기미·잡티를 집중 케어하는 브라이트닝 앰플", fullMl: 16, price: 32000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("구달 청귤 비타C 15 잡티 케어 앰플"), linkType: "search", image: "/assets/products/goodal-vitac15-ampoule.jpeg" },
  { id: "manyo-bifida-biome-ampoule", brand: "마녀공장", name: "비피다 바이옴 콤플렉스 앰플", category: "앰플", ingredients: ["비피다발효용해물", "나이아신아마이드", "히알루론산", "아데노신"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분", "주름", "기미"], rating: 4.7, feel: "촉촉", desc: "비피다 발효 성분으로 장벽을 강화하고 미백·주름까지 돕는 촉촉한 앰플", fullMl: 30, price: 23000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 비피다 바이옴 콤플렉스 앰플"), linkType: "search", image: "/assets/products/manyo-bifida-biome-ampoule.jpeg" },
  { id: "easydew-egf-melatoning-ampoule", brand: "이지듀", name: "DW-EGF 멜라토닝 원데이 앰플", category: "앰플", ingredients: ["EGF", "나이아신아마이드", "글루타치온", "아스코르빌글루코사이드"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "DW-EGF와 나이아신아마이드·글루타치온으로 미백·탄력을 케어하는 더마 앰플", fullMl: 30, price: 39000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("이지듀 DW-EGF 멜라토닝 원데이 앰플"), linkType: "search", image: "/assets/products/easydew-egf-melatoning-ampoule.jpeg" },
  { id: "centellian24-madeca-power-ampoule", brand: "센텔리안24", name: "마데카 파워 앰플", category: "앰플", ingredients: ["병풀추출물", "마데카소사이드", "나이아신아마이드", "아데노신"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["주름", "기미", "트러블"], rating: 4.5, feel: "진정", desc: "병풀 유효성분에 나이아신아마이드·아데노신을 더해 진정과 미백·주름을 잡는 이중기능성 앰플", fullMl: 30, price: 29800, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("센텔리안24 마데카 파워 앰플"), linkType: "search", image: "/assets/products/centellian24-madeca-power-ampoule.png" },
  { id: "mediheal-madecassoside-serum", brand: "메디힐", name: "마데카소사이드 흔적 리페어 세럼", category: "세럼", ingredients: ["마데카소사이드", "병풀추출물", "판테놀", "히알루론산"], forTypes: ["건성", "지성", "복합", "중성", "민감"], concerns: ["트러블", "수분", "기미"], rating: 4.3, feel: "진정", desc: "마데카소사이드가 붉은 흔적을 진정시키고 수분을 채워 결·톤을 정돈하는 세럼", fullMl: 40, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 마데카소사이드 흔적 리페어 세럼"), linkType: "search", image: "/assets/products/mediheal-madecassoside-serum.jpeg" },
  { id: "drg-red-blemish-hyalcica-serum", brand: "닥터지", name: "레드 블레미쉬 클리어 히알 시카 수딩 세럼", category: "세럼", ingredients: ["병풀추출물", "히알루론산", "판테놀", "마데카소사이드", "알란토인"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "트러블"], rating: 4.7, feel: "진정", desc: "'히알시카'로 민감 피부에 수분을 채우고 자극·흔적을 진정시키는 수분 진정 세럼", fullMl: 50, price: 33000, safety: ["저자극", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 클리어 히알 시카 수딩 세럼"), linkType: "search", image: "/assets/products/drg-red-blemish-hyalcica-serum.jpeg" },
  { id: "drg-brightening-up-sun", brand: "닥터지", name: "브라이트닝 업 선 플러스", category: "선크림", ingredients: ["징크옥사이드", "티타늄디옥사이드", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "산뜻", desc: "SPF50+ 피치베이지 톤업 선크림, 화사한 톤보정과 파데프리 마무리", fullMl: 50, price: 32000, safety: ["미백기능성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 브라이트닝 업 선 플러스"), linkType: "search", image: "/assets/products/drg-brightening-up-sun.jpg" },
  { id: "mediheal-madecassoside-sun-serum", brand: "메디힐", name: "마데카소사이드 수분 선세럼 흔적 리페어", category: "선크림", ingredients: ["나이아신아마이드", "마데카소사이드", "병풀추출물", "히알루론산"], forTypes: ["건성", "민감", "복합"], concerns: ["트러블", "수분", "기미"], rating: 4.6, feel: "촉촉", desc: "SPF50+ 세럼형 선케어, 마데카소사이드로 진정·흔적 케어와 수분을 동시에", fullMl: 50, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 마데카소사이드 수분 선세럼 흔적 리페어"), linkType: "search", image: "/assets/products/mediheal-madecassoside-sun-serum.jpeg" },
  { id: "athe-vegan-relief-sun", brand: "아떼", name: "비건 릴리프 무기자차 선크림", category: "선크림", ingredients: ["징크옥사이드", "티타늄디옥사이드", "병풀추출물", "판테놀"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분"], rating: 4.5, feel: "진정", desc: "SPF50+ 비건 무기자차 선크림, 민감 피부 진정과 자연스러운 톤보정", fullMl: 50, price: 34000, safety: ["무기자차", "비건", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아떼 비건 릴리프 무기자차 선크림"), linkType: "search", image: "/assets/products/athe-vegan-relief-sun.png" },
  { id: "daeffect-hydro-sunscreen", brand: "디에이이펙트", name: "하이드로 선스크린", category: "선크림", ingredients: ["병풀추출물", "세라마이드", "나이아신아마이드", "판테놀"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분", "주름"], rating: 4.6, feel: "촉촉", desc: "SPF50+ 더마 선크림, 시술 후에도 순한 진정·보습과 백탁 없는 밀착 마무리", fullMl: 30, price: 39000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("디에이이펙트 하이드로 선스크린"), linkType: "search", image: "/assets/products/daeffect-hydro-sunscreen.jpeg" },
  { id: "biozin-albumin-mela-toneup-sun", brand: "비오진", name: "알부민 멜라 리셋 톤업 선크림", category: "선크림", ingredients: ["티타늄디옥사이드", "나이아신아마이드", "트라넥삼산", "알부민추출물"], forTypes: ["복합", "건성", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 톤업 선크림, 알부민·트라넥삼산으로 멜라닌 케어와 화사한 톤업", fullMl: 50, price: 35000, safety: ["미백기능성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("비오진 알부민 멜라 리셋 톤업 선크림"), linkType: "search", image: "/assets/products/biozin-albumin-mela-toneup-sun.jpg" },
  { id: "scinic-enjoy-mild-sun-essence", brand: "싸이닉", name: "엔조이 슈퍼 마일드 수분 선에센스", category: "선크림", ingredients: ["에칠헥실메톡시신나메이트", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "복합", "민감"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 유기자차 선에센스, 수분 에센스처럼 촉촉하게 흡수되는 데일리 자차", fullMl: 50, price: 15000, safety: ["저자극테스트", "비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("싸이닉 엔조이 슈퍼 마일드 수분 선에센스"), linkType: "search", image: "/assets/products/scinic-enjoy-mild-sun-essence.jpg" },
  { id: "hieut-vita-waterful-sun-essence", brand: "hieut", name: "비타 워터풀 선에센스", category: "선크림", ingredients: ["나이아신아마이드", "히알루론산"], forTypes: ["건성", "복합", "중성"], concerns: ["수분"], rating: 4.4, feel: "촉촉", desc: "SPF50+ PA++++ 워터풀 선에센스, 산뜻하게 흡수되는 수분 자차", fullMl: 50, price: 22000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("hieut 비타 워터풀 선에센스"), linkType: "search", image: "/assets/products/hieut-vita-waterful-sun-essence.jpg" },
  { id: "ahc-masters-toneup-sun-serum", brand: "AHC", name: "마스터즈 톤업 선세럼", category: "선크림", ingredients: ["티타늄디옥사이드", "나이아신아마이드", "아데노신", "히알루론산"], forTypes: ["건성", "복합", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "SPF50+ 세럼형 톤업 선크림, 백탁 없이 자연스러운 데일리 톤업", fullMl: 50, price: 33000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("AHC 마스터즈 톤업 선세럼"), linkType: "search", image: "/assets/products/ahc-masters-toneup-sun-serum.jpg" },
  { id: "shingmulnara-watery-sun-gel", brand: "식물나라", name: "가벼운 수분 선 젤", category: "선크림", ingredients: ["나이아신아마이드", "알로에베라잎추출물", "히알루론산", "아데노신"], forTypes: ["지성", "복합"], concerns: ["수분"], rating: 4.4, feel: "산뜻", desc: "SPF50+ 수분 젤 선크림, 백탁 없이 산뜻하게 발리는 가벼운 데일리 자차", fullMl: 60, price: 14800, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("식물나라 가벼운 수분 선 젤 선크림"), linkType: "search", image: "/assets/products/shingmulnara-watery-sun-gel.jpg" },
  { id: "cellfusionc-spot-toning-sunscreen", brand: "셀퓨전씨", name: "잡티 토닝 썬스크린", category: "선크림", ingredients: ["티타늄디옥사이드", "징크옥사이드", "나이아신아마이드", "아데노신"], forTypes: ["지성", "복합", "민감"], concerns: ["기미"], rating: 4.5, feel: "산뜻", desc: "SPF50+ 무기자차 톤업 선크림, 잡티 케어까지 챙기는 미백·주름 기능성", fullMl: 50, price: 27900, safety: ["무기자차", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("셀퓨전씨 잡티 토닝 썬스크린"), linkType: "search", image: "/assets/products/cellfusionc-spot-toning-sunscreen.jpeg" },
  { id: "goodal-houttuynia-calming-sun", brand: "구달", name: "맑은 어성초 진정 무기자차 선크림", category: "선크림", ingredients: ["어성초추출물", "징크옥사이드", "티타늄디옥사이드", "판테놀"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블", "수분"], rating: 4.5, feel: "진정", desc: "SPF50+ 어성초 진정 무기자차 선크림, 백탁 적고 자극받은 피부를 진정", fullMl: 50, price: 20000, safety: ["무기자차", "비건", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("구달 맑은 어성초 진정 무기자차 선크림"), linkType: "search", image: "/assets/products/goodal-houttuynia-calming-sun.jpeg" },
  { id: "roundlab-birch-cleanser", brand: "라운드랩", name: "자작나무 수분 클렌저", category: "클렌징", ingredients: ["자작나무수", "히알루론산", "판테놀"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분"], rating: 4.6, feel: "촉촉", desc: "자작나무수 함유 약산성 클렌저, 당김 없이 수분감 있게 마무리", fullMl: 150, price: 15000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 자작나무 수분 클렌저"), linkType: "search", image: "/assets/products/roundlab-birch-cleanser.jpg" },
  { id: "offon-7xcica-biome-foam", brand: "오프온", name: "7X 시카 바이옴 약산성 클렌징폼", category: "클렌징", ingredients: ["병풀추출물", "바이옴", "판테놀", "티트리오일"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.5, feel: "진정", desc: "시카·바이옴 약산성 클렌징폼, 트러블 진정과 순한 세정", fullMl: 120, price: 23000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("오프온 7X 시카 바이옴 약산성 클렌징폼"), linkType: "search", image: "/assets/products/offon-7xcica-biome-foam.png" },
  { id: "roundlab-pine-cica-cleanser", brand: "라운드랩", name: "소나무 진정 시카 클렌저", category: "클렌징", ingredients: ["소나무잎추출물", "병풀추출물", "마데카소사이드", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "소나무잎·시카 폼 클렌저, 피지 세정과 자극받은 피부 진정", fullMl: 150, price: 17000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 소나무 진정 시카 클렌저"), linkType: "search", image: "/assets/products/roundlab-pine-cica-cleanser.jpeg" },
  { id: "roundlab-dokdo-bubble-foam", brand: "라운드랩", name: "1025 독도 버블 클렌징 폼", category: "클렌징", ingredients: ["해수", "병풀잎추출물", "소나무잎추출물", "히알루론산", "판테놀"], forTypes: ["지성", "복합", "중성", "민감"], concerns: ["트러블"], rating: 4.5, feel: "산뜻", desc: "해수·병풀 함유 약산성 버블 폼, 풍성한 거품으로 산뜻하게 세정", fullMl: 150, price: 13000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 1025 독도 버블 클렌징 폼"), linkType: "search", image: "/assets/products/roundlab-dokdo-bubble-foam.jpeg" },
  { id: "mediheal-derma-cream-cleanser-madeca", brand: "메디힐", name: "더마 크림 팩 클렌저 마데카소사이드", category: "클렌징", ingredients: ["마데카소사이드", "병풀잎추출물", "판테놀", "나이아신아마이드"], forTypes: ["건성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.4, feel: "촉촉", desc: "마데카소사이드 크림형 팩 클렌저, 세정과 함께 진정·장벽 보습", fullMl: 120, price: 21000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 더마 크림 팩 클렌저 마데카소사이드"), linkType: "search", image: "/assets/products/mediheal-derma-cream-cleanser-madeca.jpeg" },
  { id: "mediheal-derma-cream-cleanser-pdrn", brand: "메디힐", name: "더마 크림 팩 클렌저 피디알엔", category: "클렌징", ingredients: ["PDRN", "히알루론산", "글리세린", "장미꽃추출물"], forTypes: ["건성", "복합", "민감"], concerns: ["주름", "수분"], rating: 4.6, feel: "촉촉", desc: "PDRN 함유 쫀득한 크림형 팩 클렌저, 모공 세정과 탄력 케어", fullMl: 120, price: 21000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 더마 크림 팩 클렌저 피디알엔"), linkType: "search", image: "/assets/products/mediheal-derma-cream-cleanser-pdrn.jpeg" },
  { id: "abib-acne-heartleaf-foam", brand: "아비브", name: "아크네 폼 클렌저 어성초 폼", category: "클렌징", ingredients: ["어성초추출물", "살리실산(BHA)", "병풀추출물"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "어성초·살리실산 약산성 폼, 트러블 진정과 피지·모공 케어", fullMl: 150, price: 16000, safety: ["약산성", "저자극", "무향"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 아크네 폼 클렌저 어성초 폼"), linkType: "search", image: "/assets/products/abib-acne-heartleaf-foam.png" },
  { id: "aboutme-rice-makgeolli-foam", brand: "어바웃미", name: "쌀 막걸리 클렌징 폼", category: "클렌징", ingredients: ["쌀겨수", "쌀추출물", "갈락토미세스발효여과물", "글리세린"], forTypes: ["건성", "복합", "민감"], concerns: ["수분", "기미"], rating: 4.6, feel: "촉촉", desc: "쌀겨수·쌀 발효 성분의 쫀쫀한 거품 약산성 폼, 보습 세안과 톤 케어", fullMl: 120, price: 14000, safety: ["약산성"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("어바웃미 쌀 막걸리 클렌징 폼"), linkType: "search", image: "/assets/products/aboutme-rice-makgeolli-foam.jpeg" },
  { id: "centellian24-madeca-amino-cleanser", brand: "센텔리안24", name: "마데카 아미노산 클렌징폼", category: "클렌징", ingredients: ["병풀추출물", "마데카소사이드", "아미노산계면활성제", "판테놀"], forTypes: ["건성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.5, feel: "촉촉", desc: "마데카소사이드·아미노산 계면활성제의 약산성 저자극 폼, 진정·보습 세안", fullMl: 160, price: 18000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("센텔리안24 마데카 아미노산 클렌징폼"), linkType: "search", image: "/assets/products/centellian24-madeca-amino-cleanser.png" },
  { id: "cellfusionc-pore-sun-cleanser", brand: "셀퓨전씨", name: "포어 썬 클렌징 폼", category: "클렌징", ingredients: ["유칼립투스잎추출물", "살리실산(BHA)", "히알루론산"], forTypes: ["지성", "복합"], concerns: ["트러블"], rating: 4.5, feel: "산뜻", desc: "살리실산·유칼립투스 모공 딥클렌징 폼, 선크림·피지 세정에 특화", fullMl: 150, price: 18000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("셀퓨전씨 포어 썬 클렌징 폼"), linkType: "search", image: "/assets/products/cellfusionc-pore-sun-cleanser.jpeg" },
  { id: "abib-collagen-gel-mask", brand: "아비브", name: "콜라겐 겔 마스크 수분초 젤리", category: "마스크팩", ingredients: ["콜라겐", "히알루론산", "판테놀", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["수분", "주름"], rating: 4.7, feel: "촉촉", desc: "콜라겐·히알루론산 겔 시트, 수분과 탄력을 함께 채우는 밀착 마스크", fullMl: 30, price: 5000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 콜라겐 겔 마스크 수분초 젤리"), linkType: "search" },
  { id: "abib-heartleaf-sheet-mask", brand: "아비브", name: "약산성 pH 시트 마스크 어성초 핏", category: "마스크팩", ingredients: ["어성초추출물", "판테놀", "히알루론산", "글리세린"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "어성초 담은 약산성 투명 시트, 민감·트러블 피부를 진정시키는 데일리 마스크", fullMl: 30, price: 4000, safety: ["약산성", "저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아비브 약산성 pH 시트 마스크 어성초 핏"), linkType: "search" },
  { id: "firstlab-probiotic-mask", brand: "퍼스트랩", name: "프로바이오틱 마스크", category: "마스크팩", ingredients: ["유산균발효여과물", "나이아신아마이드", "글루타치온", "펩타이드"], forTypes: ["민감", "복합", "중성"], concerns: ["트러블", "기미", "수분"], rating: 4.5, feel: "진정", desc: "유산균·나이아신아마이드로 장벽 진정과 브라이트닝을 돕는 시트 마스크", fullMl: 25, price: 2000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("퍼스트랩 프로바이오틱 마스크"), linkType: "search" },
  { id: "dalba-vita-toning-niacinamide-mask", brand: "달바", name: "비타 토닝 나이아신아마이드 5% 마스크", category: "마스크팩", ingredients: ["비타민나무수", "나이아신아마이드", "글루타치온", "히알루론산"], forTypes: ["중성", "복합", "건성"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "나이아신아마이드 5%·비타민나무수의 미백·주름 2중 기능성 톤업 시트 마스크", fullMl: 28, price: 6000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 비타 토닝 나이아신아마이드 5% 마스크팩"), linkType: "search" },
  { id: "mediheal-dna-proatin-mask", brand: "메디힐", name: "디엔에이 프로아틴 마스크", category: "마스크팩", ingredients: ["하이드롤라이즈드콜라겐", "세라마이드", "아세틸헥사펩타이드-8", "판테놀"], forTypes: ["건성", "중성", "복합"], concerns: ["수분", "주름"], rating: 4.4, feel: "촉촉", desc: "수분단백질·세라마이드로 속건조를 케어하고 탄력을 채우는 보습 시트 마스크", fullMl: 25, price: 3000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("메디힐 디엔에이 프로아틴 마스크"), linkType: "search" },
  { id: "drg-red-blemish-soothing-mask", brand: "닥터지", name: "레드 블레미쉬 쿨 수딩 마스크", category: "마스크팩", ingredients: ["병풀추출물", "마데카소사이드", "판테놀", "히알루론산", "알란토인"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블", "수분"], rating: 4.7, feel: "진정", desc: "시카 콤플렉스로 예민해진 피부를 진정시키는 수분 진정 시트 마스크", fullMl: 30, price: 4000, safety: ["약산성", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 쿨 수딩 마스크"), linkType: "search" },
  { id: "drg-blacksnail-lifting-mask", brand: "닥터지", name: "블랙스네일 리프팅 마스크", category: "마스크팩", ingredients: ["달팽이점액여과물", "프로폴리스추출물", "히알루론산", "아데노신", "콜라겐"], forTypes: ["건성", "중성", "복합"], concerns: ["주름", "수분"], rating: 4.8, feel: "촉촉", desc: "블랙스네일·프로폴리스 영양 성분으로 탄력을 채우는 리프팅 시트 마스크", fullMl: 30, price: 3000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 블랙스네일 리프팅 마스크"), linkType: "search" },
  { id: "dalba-vegan-liftension-mask", brand: "달바", name: "비건 인텐시브 리프텐션 마스크", category: "마스크팩", ingredients: ["화이트트러플", "콜라겐", "비건세라마이드", "판테놀", "센텔라"], forTypes: ["건성", "중성", "복합"], concerns: ["주름", "수분"], rating: 4.5, feel: "촉촉", desc: "농축 탄력 앰플과 텐션업 시트의 더블 케어, 탄력을 끌어올리는 비건 리프팅 마스크", fullMl: 35, price: 8000, safety: ["비건"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 비건 인텐시브 리프텐션 마스크팩"), linkType: "search" },
  { id: "ahc-proshot-pore-eraser-mask", brand: "AHC", name: "프로샷 포어 이레이저 스피큘 세럼 인 겔 마스크", category: "마스크팩", ingredients: ["스피큘", "레티놀", "글루타치온", "나이아신아마이드"], forTypes: ["복합", "지성"], concerns: ["기미", "주름"], rating: 4.5, feel: "촉촉", desc: "스피큘과 세럼 영양을 밀착 전달하는 모공·광채 케어 하이드로겔 마스크", fullMl: 28, price: 3000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("AHC 프로샷 포어이레이저 스피큘 세럼인 겔 마스크"), linkType: "search" },
  { id: "manyo-galac-niacin-mask", brand: "마녀공장", name: "갈락 나이아신 에센스 마스크", category: "마스크팩", ingredients: ["갈락토미세스발효여과물", "나이아신아마이드", "판테놀"], forTypes: ["복합", "건성", "중성"], concerns: ["기미", "수분"], rating: 4.5, feel: "촉촉", desc: "갈락토미세스·나이아신아마이드로 투명 광채와 톤을 케어하는 에센스 시트 마스크", fullMl: 25, price: 3000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 갈락 나이아신 에센스 마스크팩"), linkType: "search" },

  // 로션·에멀전 12종 추가
  { id: "roundlab-dokdo-lotion", brand: "라운드랩", name: "1025 독도 로션", category: "로션", ingredients: ["독도해양심층수", "판테놀"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "독도해양심층수로 자극 없이 유수분 밸런스를 잡아주는 로션", fullMl: 200, price: 21000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("라운드랩 1025 독도 로션"), linkType: "search", image: "/assets/products/roundlab-dokdo-lotion.webp" },
  { id: "anua-heartleaf-lotion", brand: "아누아", name: "어성초 77 히알루론산 수분 진정 로션", category: "로션", ingredients: ["어성초추출물", "히알루론산"], forTypes: ["지성", "복합", "민감"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "어성초 77%로 트러블과 열감을 진정시키며 수분을 채우는 로션", fullMl: 200, price: 22000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("아누아 어성초 77 히알루론산 수분 진정 로션"), linkType: "search", image: "/assets/products/anua-heartleaf-lotion.webp" },
  { id: "manyo-bifida-biome-lotion", brand: "마녀공장", name: "비피다 바이옴 앰플 로션", category: "로션", ingredients: ["비피다발효용해물", "나이아신아마이드"], forTypes: ["건성", "복합", "중성", "민감"], concerns: ["수분", "주름"], rating: 4.6, feel: "촉촉", desc: "비피다 발효 성분으로 장벽을 채우는 앰플 함량 로션", fullMl: 300, price: 24000, safety: ["저자극테스트"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("마녀공장 비피다 바이옴 앰플 로션"), linkType: "search", image: "/assets/products/manyo-bifida-biome-lotion.webp" },
  { id: "missha-first-essence-lotion", brand: "미샤", name: "타임 레볼루션 더 퍼스트 에센스 로션 5X", category: "로션", ingredients: ["갈락토미세스발효여과물", "나이아신아마이드"], forTypes: ["건성", "복합", "중성"], concerns: ["주름", "기미"], rating: 4.6, feel: "촉촉", desc: "갈락토미세스 발효 에센스 함량을 높인 안티에이징 로션", fullMl: 130, price: 22000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 타임 레볼루션 더 퍼스트 에센스 로션 5X"), linkType: "search", image: "/assets/products/missha-first-essence-lotion.png" },
  { id: "drjart-cicapair-lotion", brand: "닥터자르트", name: "시카페어 인텐시브 수딩 리페어 트리트먼트 로션", category: "로션", ingredients: ["병풀추출물", "마데카소사이드"], forTypes: ["민감", "지성", "복합"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "시카 콤플렉스로 예민해진 피부 장벽을 리페어하는 진정 로션", fullMl: 150, price: 42000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터자르트 시카페어 인텐시브 수딩 리페어 트리트먼트 로션"), linkType: "search", image: "/assets/products/drjart-cicapair-lotion.webp" },
  { id: "drjart-ceramidin-lotion", brand: "닥터자르트", name: "세라마이딘 스킨 베리어 모이스처라이징 밀키 로션", category: "로션", ingredients: ["세라마이드", "히알루론산"], forTypes: ["건성", "민감", "복합"], concerns: ["수분"], rating: 4.7, feel: "보습", desc: "세라마이딘 성분으로 피부 장벽을 채우는 고보습 밀키 로션", fullMl: 50, price: 47000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터자르트 세라마이딘 스킨 베리어 모이스처라이징 밀키 로션"), linkType: "search", image: "/assets/products/drjart-ceramidin-lotion.webp" },
  { id: "biohealboh-probioderm-emulsion", brand: "바이오힐보", name: "프로바이오덤 리페어 에멀전", category: "로션", ingredients: ["병풀추출물", "프로바이오틱스"], forTypes: ["민감", "건성", "복합"], concerns: ["트러블", "수분"], rating: 4.6, feel: "진정", desc: "프로바이오틱스로 피부 장벽과 유수분 밸런스를 리페어하는 에멀전", fullMl: 150, price: 24000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("바이오힐보 프로바이오덤 리페어 에멀전"), linkType: "search", image: "/assets/products/biohealboh-probioderm-emulsion.jpeg" },
  { id: "naturerepublic-snail-emulsion", brand: "네이처리퍼블릭", name: "스네일 솔루션 에멀전", category: "로션", ingredients: ["달팽이점액여과물"], forTypes: ["건성", "복합", "중성"], concerns: ["수분", "주름"], rating: 4.4, feel: "촉촉", desc: "달팽이점액여과물로 탄력과 수분을 채우는 데일리 에멀전", fullMl: 120, price: 19000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("네이처리퍼블릭 스네일 솔루션 에멀전"), linkType: "search", image: "/assets/products/naturerepublic-snail-emulsion.jpeg" },
  { id: "bringgreen-bluebean-pdrn-lotion", brand: "브링그린", name: "블루빈 B5 PDRN 마일드 로션", category: "로션", ingredients: ["PDRN", "판테놀"], forTypes: ["건성", "민감", "복합"], concerns: ["수분", "주름"], rating: 4.5, feel: "촉촉", desc: "PDRN·판테놀로 순하게 수분과 탄력을 채우는 마일드 로션", fullMl: 230, price: 18000, safety: ["저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("브링그린 블루빈 B5 PDRN 마일드 로션"), linkType: "search", image: "/assets/products/bringgreen-bluebean-pdrn-lotion.jpeg" },
  { id: "dalba-white-truffle-lotion", brand: "달바", name: "화이트 트러플 모이스처라이징 세럼 로션", category: "로션", ingredients: ["화이트트러플추출물", "나이아신아마이드"], forTypes: ["건성", "중성", "복합"], concerns: ["수분", "기미"], rating: 4.6, feel: "촉촉", desc: "화이트 트러플 추출물로 윤기와 수분을 채우는 세럼 로션", fullMl: 100, price: 42000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("달바 화이트 트러플 모이스처라이징 세럼 로션"), linkType: "search", image: "/assets/products/dalba-white-truffle-lotion.jpeg" },
  { id: "missha-superaqua-emulsion", brand: "미샤", name: "수퍼 아쿠아 울트라 히알론 에멀전", category: "로션", ingredients: ["히알루론산"], forTypes: ["건성", "중성", "복합"], concerns: ["수분"], rating: 4.5, feel: "촉촉", desc: "히알루론산으로 촉촉함을 채우는 데일리 수분 에멀전", fullMl: 130, price: 19000, safety: [], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("미샤 수퍼 아쿠아 울트라 히알론 에멀전"), linkType: "search", image: "/assets/products/missha-superaqua-emulsion.jpeg" },
  { id: "drg-red-blemish-multi-fluid", brand: "닥터지", name: "레드 블레미쉬 멀티 플루이드", category: "로션", ingredients: ["센텔라", "시카"], forTypes: ["민감", "복합", "지성"], concerns: ["트러블"], rating: 4.6, feel: "진정", desc: "레드 블레미쉬 라인의 산뜻한 플루이드 타입 진정 로션", fullMl: 100, price: 29000, safety: ["진정", "저자극"], oliveYoungUrl: "https://www.oliveyoung.co.kr/store/search/getSearchMain.do?query=" + encodeURIComponent("닥터지 레드 블레미쉬 멀티 플루이드"), linkType: "search", image: "/assets/products/drg-red-blemish-multi-fluid.png" },
];

export type WxProfile = { temp: number; humidity: number; uv: number; dust: number };
export type Recommendation = { p: Cosmetic; reason: string };

function normType(t: string) {
  return t.replace("복합성", "복합").replace("민감성", "민감");
}

export function recommendCosmetics(
  skinTypeForRec: string,
  sensitivity: string,
  concerns: string[],
  wx: WxProfile,
  userAllergies: string[] = []
): { summary: string; items: Recommendation[] } {
  const skin = normType(skinTypeForRec);
  const dry = wx.humidity <= 45;
  const hotHumid = wx.temp >= 30 && wx.humidity >= 70;
  const hiUV = wx.uv >= 8;
  const hiDust = wx.dust >= 80;

  const scored = COSMETICS.map((p) => {
    let s = 0;
    if (p.forTypes.includes(skin)) s += 3;
    const matched = concerns.filter((c) => p.concerns.includes(c));
    s += matched.length * 2;
    s += (p.rating - 4.3) * 4;
    if (sensitivity === "민감") {
      if (p.forTypes.includes("민감")) s += 1.5;
      if (p.feel === "진정") s += 1;
    }
    if (dry && p.concerns.includes("수분")) s += 2;
    if (hotHumid) {
      if (p.feel === "산뜻") s += 1.5;
      if (["클렌징", "토너", "선크림"].includes(p.category)) s += 0.6;
    }
    if (hiUV) {
      if (p.category === "선크림") s += 2.5;
      if (p.concerns.includes("기미")) s += 1;
    }
    if (hiDust && (p.concerns.includes("트러블") || p.category === "클렌징")) s += 1;
    // 등록된 알러지 성분과 겹치는 제품은 완전히 배제하지 않고 순위만 낮춰서, 대안이 없을 때도
    // "⚠️ 주의" 표시와 함께 여전히 확인할 수 있게 한다(오탐 가능성이 있는 로컬 매칭이라 강제 제외는 과함).
    const allergyRisk = allergyRiskForProduct(userAllergies, p.ingredients, p.safety);
    if (allergyRisk.length) s -= 3;
    return { p, s, matched, allergyRisk };
  });

  scored.sort((a, b) => b.s - a.s || b.p.rating - a.p.rating);

  // 카테고리별로 가장 점수가 높은 제품 1개만 후보로 남긴다 — "카테고리별 대표" 추천이라는
  // 취지대로, 같은 카테고리(예: 토너 2개)가 중복으로 추천되지 않게 하고 클렌징폼처럼
  // 전체 경쟁에서 밀리기 쉬운 카테고리도 항상 하나는 포함되게 한다.
  const seenCategory = new Set<string>();
  const top = scored.filter(({ p }) => {
    if (seenCategory.has(p.category)) return false;
    seenCategory.add(p.category);
    return true;
  });

  const items: Recommendation[] = top.map(({ p, matched, allergyRisk }) => {
    const bits: string[] = [];
    if (allergyRisk.length) bits.push(`⚠️ ${allergyRisk.join("·")} 주의`);
    if (p.forTypes.includes(skin)) bits.push(`${skinTypeForRec} 피부 적합`);
    if (p.ingredients[0]) bits.push(`${p.ingredients[0]} 함유`);
    if (hiUV && p.category === "선크림") bits.push("강한 자외선 차단");
    else if (hiDust && p.category === "클렌징") bits.push("미세먼지 많은 날 클렌징 케어");
    else if (dry && p.concerns.includes("수분")) bits.push("건조한 기후 속보습");
    else if (hotHumid && p.feel === "산뜻") bits.push("습한 날 산뜻하게");
    else if (matched[0]) bits.push(`'${matched[0]}' 고민 케어`);
    return { p, reason: bits.slice(0, 3).join(" · ") };
  });

  const driver = hiUV ? "강한 자외선" : dry ? "건조한 공기" : hotHumid ? "고온다습" : hiDust ? "높은 미세먼지" : "쾌적한 날씨";
  const approach =
    sensitivity === "민감"
      ? "진정 성분(센텔라·판테놀)"
      : skin === "건성"
        ? "고보습(히알루론산·세라마이드)"
        : skin === "지성"
          ? "피지 케어(BHA·나이아신)"
          : "수분·톤 밸런스";
  const sun = hiUV ? " + 무기자차 선크림" : "";
  const summary = `${skinTypeForRec} + ${driver} → ${approach}${sun} → 아래 추천`;

  return { summary, items };
}

/* ── [5-4] 소용량 샘플 로직 ── */
export const SAMPLE_TIERS = [10, 20, 30, 50, 75];
const DAILY_USAGE: Record<string, number> = { 토너: 2.0, 세럼: 1.0, 앰플: 1.0, 크림: 1.5, 선크림: 2.0, 클렌징: 2.0 };
const MOIST_CATS = ["토너", "크림", "앰플", "세럼"];

export function dailyUsage(category: string) {
  return DAILY_USAGE[category] ?? 1.5;
}

// 여행 일수 + 기후로 추천 용량 티어 산출
export function recommendVolume(category: string, days: number, dryHigh: boolean, uvHigh: boolean) {
  const need = dailyUsage(category) * days * 1.2;
  let idx = SAMPLE_TIERS.findIndex((t) => t >= need);
  if (idx === -1) idx = SAMPLE_TIERS.length - 1;
  if (dryHigh && MOIST_CATS.includes(category)) idx = Math.min(SAMPLE_TIERS.length - 1, idx + 1);
  if (uvHigh && category === "선크림") idx = Math.min(SAMPLE_TIERS.length - 1, idx + 1);
  const ml = SAMPLE_TIERS[idx];
  const qty = ml >= 75 && need > 75 ? Math.ceil(need / 75) : 1;
  return { ml, qty, need: Math.round(need) };
}

// ml당 단가 기준 소용량 금액 (100원 반올림)
export function samplePrice(price: number, fullMl: number, ml: number) {
  const per = price / fullMl;
  return Math.round((per * ml) / 100) * 100;
}
